// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: proto/lifecycle_control.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LifecycleControl_Action int32

const (
	LifecycleControl_ACTION_UNSPECIFIED LifecycleControl_Action = 0
	LifecycleControl_INITIALIZE         LifecycleControl_Action = 1
	LifecycleControl_START              LifecycleControl_Action = 2
	LifecycleControl_STOP               LifecycleControl_Action = 3
	LifecycleControl_RESTART            LifecycleControl_Action = 4
	LifecycleControl_RELOAD             LifecycleControl_Action = 5
)

// Enum value maps for LifecycleControl_Action.
var (
	LifecycleControl_Action_name = map[int32]string{
		0: "ACTION_UNSPECIFIED",
		1: "INITIALIZE",
		2: "START",
		3: "STOP",
		4: "RESTART",
		5: "RELOAD",
	}
	LifecycleControl_Action_value = map[string]int32{
		"ACTION_UNSPECIFIED": 0,
		"INITIALIZE":         1,
		"START":              2,
		"STOP":               3,
		"RESTART":            4,
		"RELOAD":             5,
	}
)

func (x LifecycleControl_Action) Enum() *LifecycleControl_Action {
	p := new(LifecycleControl_Action)
	*p = x
	return p
}

func (x LifecycleControl_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LifecycleControl_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_lifecycle_control_proto_enumTypes[0].Descriptor()
}

func (LifecycleControl_Action) Type() protoreflect.EnumType {
	return &file_proto_lifecycle_control_proto_enumTypes[0]
}

func (x LifecycleControl_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LifecycleControl_Action.Descriptor instead.
func (LifecycleControl_Action) EnumDescriptor() ([]byte, []int) {
	return file_proto_lifecycle_control_proto_rawDescGZIP(), []int{0, 0}
}

type LifecycleControl struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	AgentId string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Enum for supported lifecycle actions
	Action        LifecycleControl_Action `protobuf:"varint,2,opt,name=action,proto3,enum=proto.LifecycleControl_Action" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LifecycleControl) Reset() {
	*x = LifecycleControl{}
	mi := &file_proto_lifecycle_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LifecycleControl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LifecycleControl) ProtoMessage() {}

func (x *LifecycleControl) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lifecycle_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LifecycleControl.ProtoReflect.Descriptor instead.
func (*LifecycleControl) Descriptor() ([]byte, []int) {
	return file_proto_lifecycle_control_proto_rawDescGZIP(), []int{0}
}

func (x *LifecycleControl) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *LifecycleControl) GetAction() LifecycleControl_Action {
	if x != nil {
		return x.Action
	}
	return LifecycleControl_ACTION_UNSPECIFIED
}

var File_proto_lifecycle_control_proto protoreflect.FileDescriptor

const file_proto_lifecycle_control_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/lifecycle_control.proto\x12\x05proto\"\xc5\x01\n" +
	"\x10LifecycleControl\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x126\n" +
	"\x06action\x18\x02 \x01(\x0e2\x1e.proto.LifecycleControl.ActionR\x06action\"^\n" +
	"\x06Action\x12\x16\n" +
	"\x12ACTION_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"INITIALIZE\x10\x01\x12\t\n" +
	"\x05START\x10\x02\x12\b\n" +
	"\x04STOP\x10\x03\x12\v\n" +
	"\aRESTART\x10\x04\x12\n" +
	"\n" +
	"\x06RELOAD\x10\x05B/Z-github.com/goppydae/gapi/internal/proto;protob\x06proto3"

var (
	file_proto_lifecycle_control_proto_rawDescOnce sync.Once
	file_proto_lifecycle_control_proto_rawDescData []byte
)

func file_proto_lifecycle_control_proto_rawDescGZIP() []byte {
	file_proto_lifecycle_control_proto_rawDescOnce.Do(func() {
		file_proto_lifecycle_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_lifecycle_control_proto_rawDesc), len(file_proto_lifecycle_control_proto_rawDesc)))
	})
	return file_proto_lifecycle_control_proto_rawDescData
}

var file_proto_lifecycle_control_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_lifecycle_control_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_lifecycle_control_proto_goTypes = []any{
	(LifecycleControl_Action)(0), // 0: proto.LifecycleControl.Action
	(*LifecycleControl)(nil),     // 1: proto.LifecycleControl
}
var file_proto_lifecycle_control_proto_depIdxs = []int32{
	0, // 0: proto.LifecycleControl.action:type_name -> proto.LifecycleControl.Action
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_lifecycle_control_proto_init() }
func file_proto_lifecycle_control_proto_init() {
	if File_proto_lifecycle_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_lifecycle_control_proto_rawDesc), len(file_proto_lifecycle_control_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_lifecycle_control_proto_goTypes,
		DependencyIndexes: file_proto_lifecycle_control_proto_depIdxs,
		EnumInfos:         file_proto_lifecycle_control_proto_enumTypes,
		MessageInfos:      file_proto_lifecycle_control_proto_msgTypes,
	}.Build()
	File_proto_lifecycle_control_proto = out.File
	file_proto_lifecycle_control_proto_goTypes = nil
	file_proto_lifecycle_control_proto_depIdxs = nil
}
