// Copyright (c) 2025 Steven Verhelle (enqack)
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: goblin/v1/cluster_event.proto

package goblinv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ClusterEvent is the gossip wire form of an eventbus Event
// (GOBLIN-DIV-039). The envelope is typed so buf breaking covers it;
// payload is a google.protobuf.Struct because the in-process contract
// is map[string]interface{} - per-topic payload schemas are a future
// eventbus API decision, not smuggled in here. Serf bounds user events
// at 512 bytes (name + payload); the encoder fails loudly rather than
// letting an oversized event truncate or vanish.
type ClusterEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	Payload       *structpb.Struct       `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	NodeId        string                 `protobuf:"bytes,6,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterEvent) Reset() {
	*x = ClusterEvent{}
	mi := &file_goblin_v1_cluster_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterEvent) ProtoMessage() {}

func (x *ClusterEvent) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_cluster_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterEvent.ProtoReflect.Descriptor instead.
func (*ClusterEvent) Descriptor() ([]byte, []int) {
	return file_goblin_v1_cluster_event_proto_rawDescGZIP(), []int{0}
}

func (x *ClusterEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ClusterEvent) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ClusterEvent) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ClusterEvent) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ClusterEvent) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClusterEvent) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ClusterEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_goblin_v1_cluster_event_proto protoreflect.FileDescriptor

const file_goblin_v1_cluster_event_proto_rawDesc = "" +
	"\n" +
	"\x1dgoblin/v1/cluster_event.proto\x12\tgoblin.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xec\x01\n" +
	"\fClusterEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x121\n" +
	"\apayload\x18\x05 \x01(\v2\x17.google.protobuf.StructR\apayload\x12\x17\n" +
	"\anode_id\x18\x06 \x01(\tR\x06nodeId\x128\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ttimestampB+Z)github.com/goppydae/goblin/proto;goblinv1b\x06proto3"

var (
	file_goblin_v1_cluster_event_proto_rawDescOnce sync.Once
	file_goblin_v1_cluster_event_proto_rawDescData []byte
)

func file_goblin_v1_cluster_event_proto_rawDescGZIP() []byte {
	file_goblin_v1_cluster_event_proto_rawDescOnce.Do(func() {
		file_goblin_v1_cluster_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_goblin_v1_cluster_event_proto_rawDesc), len(file_goblin_v1_cluster_event_proto_rawDesc)))
	})
	return file_goblin_v1_cluster_event_proto_rawDescData
}

var file_goblin_v1_cluster_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_goblin_v1_cluster_event_proto_goTypes = []any{
	(*ClusterEvent)(nil),          // 0: goblin.v1.ClusterEvent
	(*structpb.Struct)(nil),       // 1: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_goblin_v1_cluster_event_proto_depIdxs = []int32{
	1, // 0: goblin.v1.ClusterEvent.payload:type_name -> google.protobuf.Struct
	2, // 1: goblin.v1.ClusterEvent.timestamp:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_goblin_v1_cluster_event_proto_init() }
func file_goblin_v1_cluster_event_proto_init() {
	if File_goblin_v1_cluster_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_goblin_v1_cluster_event_proto_rawDesc), len(file_goblin_v1_cluster_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_goblin_v1_cluster_event_proto_goTypes,
		DependencyIndexes: file_goblin_v1_cluster_event_proto_depIdxs,
		MessageInfos:      file_goblin_v1_cluster_event_proto_msgTypes,
	}.Build()
	File_goblin_v1_cluster_event_proto = out.File
	file_goblin_v1_cluster_event_proto_goTypes = nil
	file_goblin_v1_cluster_event_proto_depIdxs = nil
}
