// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: goblin/v1/fsm_snapshot.proto

package goblinv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FSMNamespaceState is one namespace's key/value state plus the CAS
// version counters for the same keys. Kept as two parallel maps rather
// than one map of a Value+Version message so the wire shape matches the
// FSM's own in-memory layout (state map, versions map) with no
// per-entry wrapper message.
type FSMNamespaceState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        map[string][]byte      `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Versions      map[string]uint64      `protobuf:"bytes,2,rep,name=versions,proto3" json:"versions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FSMNamespaceState) Reset() {
	*x = FSMNamespaceState{}
	mi := &file_goblin_v1_fsm_snapshot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FSMNamespaceState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FSMNamespaceState) ProtoMessage() {}

func (x *FSMNamespaceState) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_fsm_snapshot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FSMNamespaceState.ProtoReflect.Descriptor instead.
func (*FSMNamespaceState) Descriptor() ([]byte, []int) {
	return file_goblin_v1_fsm_snapshot_proto_rawDescGZIP(), []int{0}
}

func (x *FSMNamespaceState) GetValues() map[string][]byte {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *FSMNamespaceState) GetVersions() map[string]uint64 {
	if x != nil {
		return x.Versions
	}
	return nil
}

// FSMSnapshot is the entire Raft FSM state as shipped to a joining node
// or written to the local snapshot store.
type FSMSnapshot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Namespace name -> that namespace's state.
	Namespaces map[string]*FSMNamespaceState `protobuf:"bytes,1,rep,name=namespaces,proto3" json:"namespaces,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Instance UUID (canonical string form) -> marshalled
	// goblin.v1.AgentInstance bytes. The FSM holds these as typed
	// AgentInstance messages; fsm.go marshals each one when it takes a
	// snapshot and unmarshals it again on restore. They are carried as
	// bytes rather than a nested AgentInstance field so this message does
	// not have to import the instance schema.
	Instances map[string][]byte `protobuf:"bytes,2,rep,name=instances,proto3" json:"instances,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Every instance UUID ever terminated. Append-only forever (operator
	// decision 2026-07-28): a tombstoned UUID is never reused.
	Tombstones []string `protobuf:"bytes,3,rep,name=tombstones,proto3" json:"tombstones,omitempty"`
	// Instance UUID (canonical string form) -> marshalled
	// goblin.v1.MigrationRecord bytes for in-flight migrations. Same
	// rationale as instances: typed messages in the FSM, marshalled into
	// the snapshot and unmarshalled on restore, kept as bytes so this
	// message does not have to import their schema.
	Migrations map[string][]byte `protobuf:"bytes,4,rep,name=migrations,proto3" json:"migrations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Operator key id -> marshalled goblin.v1.OperatorKey bytes. Same
	// rationale as instances and migrations: typed messages in the FSM,
	// marshalled into the snapshot and unmarshalled on restore, kept as
	// bytes so this message does not have to import their schema.
	OperatorKeys map[string][]byte `protobuf:"bytes,5,rep,name=operator_keys,json=operatorKeys,proto3" json:"operator_keys,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// The registry's monotone serial. It rides the snapshot because it is
	// the replay guard for signed changes: a leader restored from a
	// snapshot that forgot the serial would accept a change already
	// applied.
	OperatorRegistrySerial uint64 `protobuf:"varint,6,opt,name=operator_registry_serial,json=operatorRegistrySerial,proto3" json:"operator_registry_serial,omitempty"`
	// Marshalled goblin.v1.OperatorKeySeed - the founding key set. Unsigned,
	// because a seed is authorized by the registry being empty rather than
	// by a signature; that is exactly why the restoring node must compare it
	// against its OWN configured keys instead of trusting it. Empty when the
	// registry is empty.
	OperatorKeySeed []byte `protobuf:"bytes,7,opt,name=operator_key_seed,json=operatorKeySeed,proto3" json:"operator_key_seed,omitempty"`
	// Marshalled goblin.v1.OperatorKeyChange records, in the order they were
	// applied. Only changes that actually mutated the registry appear: a
	// re-seed of an identical set and an ADD of an already-registered id are
	// both no-ops that do not bump the serial, so including them would make
	// the replay diverge from the apply path it is reproducing.
	OperatorKeyChain [][]byte `protobuf:"bytes,8,rep,name=operator_key_chain,json=operatorKeyChain,proto3" json:"operator_key_chain,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FSMSnapshot) Reset() {
	*x = FSMSnapshot{}
	mi := &file_goblin_v1_fsm_snapshot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FSMSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FSMSnapshot) ProtoMessage() {}

func (x *FSMSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_fsm_snapshot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FSMSnapshot.ProtoReflect.Descriptor instead.
func (*FSMSnapshot) Descriptor() ([]byte, []int) {
	return file_goblin_v1_fsm_snapshot_proto_rawDescGZIP(), []int{1}
}

func (x *FSMSnapshot) GetNamespaces() map[string]*FSMNamespaceState {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

func (x *FSMSnapshot) GetInstances() map[string][]byte {
	if x != nil {
		return x.Instances
	}
	return nil
}

func (x *FSMSnapshot) GetTombstones() []string {
	if x != nil {
		return x.Tombstones
	}
	return nil
}

func (x *FSMSnapshot) GetMigrations() map[string][]byte {
	if x != nil {
		return x.Migrations
	}
	return nil
}

func (x *FSMSnapshot) GetOperatorKeys() map[string][]byte {
	if x != nil {
		return x.OperatorKeys
	}
	return nil
}

func (x *FSMSnapshot) GetOperatorRegistrySerial() uint64 {
	if x != nil {
		return x.OperatorRegistrySerial
	}
	return 0
}

func (x *FSMSnapshot) GetOperatorKeySeed() []byte {
	if x != nil {
		return x.OperatorKeySeed
	}
	return nil
}

func (x *FSMSnapshot) GetOperatorKeyChain() [][]byte {
	if x != nil {
		return x.OperatorKeyChain
	}
	return nil
}

var File_goblin_v1_fsm_snapshot_proto protoreflect.FileDescriptor

const file_goblin_v1_fsm_snapshot_proto_rawDesc = "" +
	"\n" +
	"\x1cgoblin/v1/fsm_snapshot.proto\x12\tgoblin.v1\"\x95\x02\n" +
	"\x11FSMNamespaceState\x12@\n" +
	"\x06values\x18\x01 \x03(\v2(.goblin.v1.FSMNamespaceState.ValuesEntryR\x06values\x12F\n" +
	"\bversions\x18\x02 \x03(\v2*.goblin.v1.FSMNamespaceState.VersionsEntryR\bversions\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\x1a;\n" +
	"\rVersionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\"\x80\x06\n" +
	"\vFSMSnapshot\x12F\n" +
	"\n" +
	"namespaces\x18\x01 \x03(\v2&.goblin.v1.FSMSnapshot.NamespacesEntryR\n" +
	"namespaces\x12C\n" +
	"\tinstances\x18\x02 \x03(\v2%.goblin.v1.FSMSnapshot.InstancesEntryR\tinstances\x12\x1e\n" +
	"\n" +
	"tombstones\x18\x03 \x03(\tR\n" +
	"tombstones\x12F\n" +
	"\n" +
	"migrations\x18\x04 \x03(\v2&.goblin.v1.FSMSnapshot.MigrationsEntryR\n" +
	"migrations\x12M\n" +
	"\roperator_keys\x18\x05 \x03(\v2(.goblin.v1.FSMSnapshot.OperatorKeysEntryR\foperatorKeys\x128\n" +
	"\x18operator_registry_serial\x18\x06 \x01(\x04R\x16operatorRegistrySerial\x12*\n" +
	"\x11operator_key_seed\x18\a \x01(\fR\x0foperatorKeySeed\x12,\n" +
	"\x12operator_key_chain\x18\b \x03(\fR\x10operatorKeyChain\x1a[\n" +
	"\x0fNamespacesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.goblin.v1.FSMNamespaceStateR\x05value:\x028\x01\x1a<\n" +
	"\x0eInstancesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\x1a=\n" +
	"\x0fMigrationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\x1a?\n" +
	"\x11OperatorKeysEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01B+Z)github.com/goppydae/goblin/proto;goblinv1b\x06proto3"

var (
	file_goblin_v1_fsm_snapshot_proto_rawDescOnce sync.Once
	file_goblin_v1_fsm_snapshot_proto_rawDescData []byte
)

func file_goblin_v1_fsm_snapshot_proto_rawDescGZIP() []byte {
	file_goblin_v1_fsm_snapshot_proto_rawDescOnce.Do(func() {
		file_goblin_v1_fsm_snapshot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_goblin_v1_fsm_snapshot_proto_rawDesc), len(file_goblin_v1_fsm_snapshot_proto_rawDesc)))
	})
	return file_goblin_v1_fsm_snapshot_proto_rawDescData
}

var file_goblin_v1_fsm_snapshot_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_goblin_v1_fsm_snapshot_proto_goTypes = []any{
	(*FSMNamespaceState)(nil), // 0: goblin.v1.FSMNamespaceState
	(*FSMSnapshot)(nil),       // 1: goblin.v1.FSMSnapshot
	nil,                       // 2: goblin.v1.FSMNamespaceState.ValuesEntry
	nil,                       // 3: goblin.v1.FSMNamespaceState.VersionsEntry
	nil,                       // 4: goblin.v1.FSMSnapshot.NamespacesEntry
	nil,                       // 5: goblin.v1.FSMSnapshot.InstancesEntry
	nil,                       // 6: goblin.v1.FSMSnapshot.MigrationsEntry
	nil,                       // 7: goblin.v1.FSMSnapshot.OperatorKeysEntry
}
var file_goblin_v1_fsm_snapshot_proto_depIdxs = []int32{
	2, // 0: goblin.v1.FSMNamespaceState.values:type_name -> goblin.v1.FSMNamespaceState.ValuesEntry
	3, // 1: goblin.v1.FSMNamespaceState.versions:type_name -> goblin.v1.FSMNamespaceState.VersionsEntry
	4, // 2: goblin.v1.FSMSnapshot.namespaces:type_name -> goblin.v1.FSMSnapshot.NamespacesEntry
	5, // 3: goblin.v1.FSMSnapshot.instances:type_name -> goblin.v1.FSMSnapshot.InstancesEntry
	6, // 4: goblin.v1.FSMSnapshot.migrations:type_name -> goblin.v1.FSMSnapshot.MigrationsEntry
	7, // 5: goblin.v1.FSMSnapshot.operator_keys:type_name -> goblin.v1.FSMSnapshot.OperatorKeysEntry
	0, // 6: goblin.v1.FSMSnapshot.NamespacesEntry.value:type_name -> goblin.v1.FSMNamespaceState
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_goblin_v1_fsm_snapshot_proto_init() }
func file_goblin_v1_fsm_snapshot_proto_init() {
	if File_goblin_v1_fsm_snapshot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_goblin_v1_fsm_snapshot_proto_rawDesc), len(file_goblin_v1_fsm_snapshot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_goblin_v1_fsm_snapshot_proto_goTypes,
		DependencyIndexes: file_goblin_v1_fsm_snapshot_proto_depIdxs,
		MessageInfos:      file_goblin_v1_fsm_snapshot_proto_msgTypes,
	}.Build()
	File_goblin_v1_fsm_snapshot_proto = out.File
	file_goblin_v1_fsm_snapshot_proto_goTypes = nil
	file_goblin_v1_fsm_snapshot_proto_depIdxs = nil
}
