// Copyright (c) 2025 Steven Verhelle (enqack)
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: goblin/v1/migration.proto

package goblinv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CheckpointFetchStatus is why a fetch did or did not proceed. An enum
// rather than a message string: the destination branches on this, and
// branching on prose is how retry logic rots.
type CheckpointFetchStatus int32

const (
	// Rejected by the receiver: a response decoded from an unknown or
	// truncated writer must never read as success.
	CheckpointFetchStatus_CHECKPOINT_FETCH_STATUS_UNSPECIFIED CheckpointFetchStatus = 0
	CheckpointFetchStatus_CHECKPOINT_FETCH_STATUS_OK          CheckpointFetchStatus = 1
	// No image for this {instance_uuid, epoch}.
	CheckpointFetchStatus_CHECKPOINT_FETCH_STATUS_NOT_FOUND CheckpointFetchStatus = 2
	// Token missing, expired, or lacking the migrate right.
	CheckpointFetchStatus_CHECKPOINT_FETCH_STATUS_UNAUTHORIZED CheckpointFetchStatus = 3
	// The source could not read its own image directory.
	CheckpointFetchStatus_CHECKPOINT_FETCH_STATUS_INTERNAL CheckpointFetchStatus = 4
)

// Enum value maps for CheckpointFetchStatus.
var (
	CheckpointFetchStatus_name = map[int32]string{
		0: "CHECKPOINT_FETCH_STATUS_UNSPECIFIED",
		1: "CHECKPOINT_FETCH_STATUS_OK",
		2: "CHECKPOINT_FETCH_STATUS_NOT_FOUND",
		3: "CHECKPOINT_FETCH_STATUS_UNAUTHORIZED",
		4: "CHECKPOINT_FETCH_STATUS_INTERNAL",
	}
	CheckpointFetchStatus_value = map[string]int32{
		"CHECKPOINT_FETCH_STATUS_UNSPECIFIED":  0,
		"CHECKPOINT_FETCH_STATUS_OK":           1,
		"CHECKPOINT_FETCH_STATUS_NOT_FOUND":    2,
		"CHECKPOINT_FETCH_STATUS_UNAUTHORIZED": 3,
		"CHECKPOINT_FETCH_STATUS_INTERNAL":     4,
	}
)

func (x CheckpointFetchStatus) Enum() *CheckpointFetchStatus {
	p := new(CheckpointFetchStatus)
	*p = x
	return p
}

func (x CheckpointFetchStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CheckpointFetchStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_goblin_v1_migration_proto_enumTypes[0].Descriptor()
}

func (CheckpointFetchStatus) Type() protoreflect.EnumType {
	return &file_goblin_v1_migration_proto_enumTypes[0]
}

func (x CheckpointFetchStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CheckpointFetchStatus.Descriptor instead.
func (CheckpointFetchStatus) EnumDescriptor() ([]byte, []int) {
	return file_goblin_v1_migration_proto_rawDescGZIP(), []int{0}
}

// CheckpointFetchRequest asks a source node for one instance's image.
type CheckpointFetchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Subject instance. Stable across migration - that is the whole
	// point - so it identifies the image without naming a location.
	InstanceUuid []byte `protobuf:"bytes,1,opt,name=instance_uuid,json=instanceUuid,proto3" json:"instance_uuid,omitempty"`
	// Which checkpoint of that instance. Increments per dump, so a
	// retried migration never collides with an earlier image.
	CheckpointEpoch uint64 `protobuf:"varint,2,opt,name=checkpoint_epoch,json=checkpointEpoch,proto3" json:"checkpoint_epoch,omitempty"`
	// Serialized gapi.v1.CapabilityToken authorizing the fetch. Carried
	// as opaque bytes because the signature covers the literal payload
	// bytes; re-encoding it here would invalidate the signature.
	CapabilityToken []byte `protobuf:"bytes,3,opt,name=capability_token,json=capabilityToken,proto3" json:"capability_token,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CheckpointFetchRequest) Reset() {
	*x = CheckpointFetchRequest{}
	mi := &file_goblin_v1_migration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointFetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointFetchRequest) ProtoMessage() {}

func (x *CheckpointFetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_migration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointFetchRequest.ProtoReflect.Descriptor instead.
func (*CheckpointFetchRequest) Descriptor() ([]byte, []int) {
	return file_goblin_v1_migration_proto_rawDescGZIP(), []int{0}
}

func (x *CheckpointFetchRequest) GetInstanceUuid() []byte {
	if x != nil {
		return x.InstanceUuid
	}
	return nil
}

func (x *CheckpointFetchRequest) GetCheckpointEpoch() uint64 {
	if x != nil {
		return x.CheckpointEpoch
	}
	return 0
}

func (x *CheckpointFetchRequest) GetCapabilityToken() []byte {
	if x != nil {
		return x.CapabilityToken
	}
	return nil
}

// CheckpointFile is one image file in the manifest. Sizes are declared
// up front so the destination knows exactly how many bytes to expect
// per file and can detect truncation rather than inferring completion
// from a closed stream.
type CheckpointFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Size          uint64                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckpointFile) Reset() {
	*x = CheckpointFile{}
	mi := &file_goblin_v1_migration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointFile) ProtoMessage() {}

func (x *CheckpointFile) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_migration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointFile.ProtoReflect.Descriptor instead.
func (*CheckpointFile) Descriptor() ([]byte, []int) {
	return file_goblin_v1_migration_proto_rawDescGZIP(), []int{1}
}

func (x *CheckpointFile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CheckpointFile) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

// CheckpointFetchResponse is the header sent before any image bytes.
// On OK the source then writes each manifest file's contents in
// manifest order, with no framing between them - the declared sizes are
// the framing.
type CheckpointFetchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        CheckpointFetchStatus  `protobuf:"varint,1,opt,name=status,proto3,enum=goblin.v1.CheckpointFetchStatus" json:"status,omitempty"`
	Files         []*CheckpointFile      `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckpointFetchResponse) Reset() {
	*x = CheckpointFetchResponse{}
	mi := &file_goblin_v1_migration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointFetchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointFetchResponse) ProtoMessage() {}

func (x *CheckpointFetchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_migration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointFetchResponse.ProtoReflect.Descriptor instead.
func (*CheckpointFetchResponse) Descriptor() ([]byte, []int) {
	return file_goblin_v1_migration_proto_rawDescGZIP(), []int{2}
}

func (x *CheckpointFetchResponse) GetStatus() CheckpointFetchStatus {
	if x != nil {
		return x.Status
	}
	return CheckpointFetchStatus_CHECKPOINT_FETCH_STATUS_UNSPECIFIED
}

func (x *CheckpointFetchResponse) GetFiles() []*CheckpointFile {
	if x != nil {
		return x.Files
	}
	return nil
}

var File_goblin_v1_migration_proto protoreflect.FileDescriptor

const file_goblin_v1_migration_proto_rawDesc = "" +
	"\n" +
	"\x19goblin/v1/migration.proto\x12\tgoblin.v1\"\x93\x01\n" +
	"\x16CheckpointFetchRequest\x12#\n" +
	"\rinstance_uuid\x18\x01 \x01(\fR\finstanceUuid\x12)\n" +
	"\x10checkpoint_epoch\x18\x02 \x01(\x04R\x0fcheckpointEpoch\x12)\n" +
	"\x10capability_token\x18\x03 \x01(\fR\x0fcapabilityToken\"8\n" +
	"\x0eCheckpointFile\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x04R\x04size\"\x84\x01\n" +
	"\x17CheckpointFetchResponse\x128\n" +
	"\x06status\x18\x01 \x01(\x0e2 .goblin.v1.CheckpointFetchStatusR\x06status\x12/\n" +
	"\x05files\x18\x02 \x03(\v2\x19.goblin.v1.CheckpointFileR\x05files*\xd7\x01\n" +
	"\x15CheckpointFetchStatus\x12'\n" +
	"#CHECKPOINT_FETCH_STATUS_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aCHECKPOINT_FETCH_STATUS_OK\x10\x01\x12%\n" +
	"!CHECKPOINT_FETCH_STATUS_NOT_FOUND\x10\x02\x12(\n" +
	"$CHECKPOINT_FETCH_STATUS_UNAUTHORIZED\x10\x03\x12$\n" +
	" CHECKPOINT_FETCH_STATUS_INTERNAL\x10\x04B+Z)github.com/goppydae/goblin/proto;goblinv1b\x06proto3"

var (
	file_goblin_v1_migration_proto_rawDescOnce sync.Once
	file_goblin_v1_migration_proto_rawDescData []byte
)

func file_goblin_v1_migration_proto_rawDescGZIP() []byte {
	file_goblin_v1_migration_proto_rawDescOnce.Do(func() {
		file_goblin_v1_migration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_goblin_v1_migration_proto_rawDesc), len(file_goblin_v1_migration_proto_rawDesc)))
	})
	return file_goblin_v1_migration_proto_rawDescData
}

var file_goblin_v1_migration_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_goblin_v1_migration_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_goblin_v1_migration_proto_goTypes = []any{
	(CheckpointFetchStatus)(0),      // 0: goblin.v1.CheckpointFetchStatus
	(*CheckpointFetchRequest)(nil),  // 1: goblin.v1.CheckpointFetchRequest
	(*CheckpointFile)(nil),          // 2: goblin.v1.CheckpointFile
	(*CheckpointFetchResponse)(nil), // 3: goblin.v1.CheckpointFetchResponse
}
var file_goblin_v1_migration_proto_depIdxs = []int32{
	0, // 0: goblin.v1.CheckpointFetchResponse.status:type_name -> goblin.v1.CheckpointFetchStatus
	2, // 1: goblin.v1.CheckpointFetchResponse.files:type_name -> goblin.v1.CheckpointFile
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_goblin_v1_migration_proto_init() }
func file_goblin_v1_migration_proto_init() {
	if File_goblin_v1_migration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_goblin_v1_migration_proto_rawDesc), len(file_goblin_v1_migration_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_goblin_v1_migration_proto_goTypes,
		DependencyIndexes: file_goblin_v1_migration_proto_depIdxs,
		EnumInfos:         file_goblin_v1_migration_proto_enumTypes,
		MessageInfos:      file_goblin_v1_migration_proto_msgTypes,
	}.Build()
	File_goblin_v1_migration_proto = out.File
	file_goblin_v1_migration_proto_goTypes = nil
	file_goblin_v1_migration_proto_depIdxs = nil
}
