// Copyright (c) 2025 Steven Verhelle (enqack)
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: goblin/v1/node_rpc.proto

package goblinv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NodeStartAgentInstanceRequest instantiates and starts a spec's agent
// type under instance_id. spec is required: the node has no other way
// to learn which agent type to instantiate.
type NodeStartAgentInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Spec          *AgentSpec             `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeStartAgentInstanceRequest) Reset() {
	*x = NodeStartAgentInstanceRequest{}
	mi := &file_goblin_v1_node_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStartAgentInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStartAgentInstanceRequest) ProtoMessage() {}

func (x *NodeStartAgentInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_node_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStartAgentInstanceRequest.ProtoReflect.Descriptor instead.
func (*NodeStartAgentInstanceRequest) Descriptor() ([]byte, []int) {
	return file_goblin_v1_node_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *NodeStartAgentInstanceRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *NodeStartAgentInstanceRequest) GetSpec() *AgentSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

// NodeStartAgentInstanceResponse reports the instance that was started
// rather than a formatted sentence.
type NodeStartAgentInstanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeStartAgentInstanceResponse) Reset() {
	*x = NodeStartAgentInstanceResponse{}
	mi := &file_goblin_v1_node_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStartAgentInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStartAgentInstanceResponse) ProtoMessage() {}

func (x *NodeStartAgentInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_node_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStartAgentInstanceResponse.ProtoReflect.Descriptor instead.
func (*NodeStartAgentInstanceResponse) Descriptor() ([]byte, []int) {
	return file_goblin_v1_node_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *NodeStartAgentInstanceResponse) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

// NodeStopAgentInstanceRequest stops and deregisters an instance.
type NodeStopAgentInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeStopAgentInstanceRequest) Reset() {
	*x = NodeStopAgentInstanceRequest{}
	mi := &file_goblin_v1_node_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStopAgentInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStopAgentInstanceRequest) ProtoMessage() {}

func (x *NodeStopAgentInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_node_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStopAgentInstanceRequest.ProtoReflect.Descriptor instead.
func (*NodeStopAgentInstanceRequest) Descriptor() ([]byte, []int) {
	return file_goblin_v1_node_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *NodeStopAgentInstanceRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

// NodeStopAgentInstanceResponse reports the instance that was stopped.
// already_stopped distinguishes a real stop from the no-op case where
// the instance was already gone - both succeed, but a caller may care
// which happened.
type NodeStopAgentInstanceResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InstanceId     string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	AlreadyStopped bool                   `protobuf:"varint,2,opt,name=already_stopped,json=alreadyStopped,proto3" json:"already_stopped,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NodeStopAgentInstanceResponse) Reset() {
	*x = NodeStopAgentInstanceResponse{}
	mi := &file_goblin_v1_node_rpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStopAgentInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStopAgentInstanceResponse) ProtoMessage() {}

func (x *NodeStopAgentInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_node_rpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStopAgentInstanceResponse.ProtoReflect.Descriptor instead.
func (*NodeStopAgentInstanceResponse) Descriptor() ([]byte, []int) {
	return file_goblin_v1_node_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *NodeStopAgentInstanceResponse) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *NodeStopAgentInstanceResponse) GetAlreadyStopped() bool {
	if x != nil {
		return x.AlreadyStopped
	}
	return false
}

// NodeSignalAgentInstanceRequest delivers an authorized signal to an
// instance on this node. instance_id is the canonical UUID string, as
// goblinctl prints it - not the raw bytes spec_uuid/instance_uuid use
// elsewhere in this schema, matching SchedulerRPC's
// SignalAgentInstanceRequest.
type NodeSignalAgentInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Signum        int32                  `protobuf:"varint,2,opt,name=signum,proto3" json:"signum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeSignalAgentInstanceRequest) Reset() {
	*x = NodeSignalAgentInstanceRequest{}
	mi := &file_goblin_v1_node_rpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeSignalAgentInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeSignalAgentInstanceRequest) ProtoMessage() {}

func (x *NodeSignalAgentInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_node_rpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeSignalAgentInstanceRequest.ProtoReflect.Descriptor instead.
func (*NodeSignalAgentInstanceRequest) Descriptor() ([]byte, []int) {
	return file_goblin_v1_node_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *NodeSignalAgentInstanceRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *NodeSignalAgentInstanceRequest) GetSignum() int32 {
	if x != nil {
		return x.Signum
	}
	return 0
}

// NodeSignalAgentInstanceResponse reports the delivered signal rather
// than a formatted sentence.
type NodeSignalAgentInstanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Signum        int32                  `protobuf:"varint,2,opt,name=signum,proto3" json:"signum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeSignalAgentInstanceResponse) Reset() {
	*x = NodeSignalAgentInstanceResponse{}
	mi := &file_goblin_v1_node_rpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeSignalAgentInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeSignalAgentInstanceResponse) ProtoMessage() {}

func (x *NodeSignalAgentInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_node_rpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeSignalAgentInstanceResponse.ProtoReflect.Descriptor instead.
func (*NodeSignalAgentInstanceResponse) Descriptor() ([]byte, []int) {
	return file_goblin_v1_node_rpc_proto_rawDescGZIP(), []int{5}
}

func (x *NodeSignalAgentInstanceResponse) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *NodeSignalAgentInstanceResponse) GetSignum() int32 {
	if x != nil {
		return x.Signum
	}
	return 0
}

// NodeCheckpointAgentInstanceRequest asks a node to dump one instance
// it is running (GOBLIN-DIV-031). instance_id travels for diagnostics
// only - the checkpoint store is keyed by {instance_uuid, epoch}.
type NodeCheckpointAgentInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	InstanceUuid  []byte                 `protobuf:"bytes,2,opt,name=instance_uuid,json=instanceUuid,proto3" json:"instance_uuid,omitempty"`
	Epoch         uint64                 `protobuf:"varint,3,opt,name=epoch,proto3" json:"epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeCheckpointAgentInstanceRequest) Reset() {
	*x = NodeCheckpointAgentInstanceRequest{}
	mi := &file_goblin_v1_node_rpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeCheckpointAgentInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeCheckpointAgentInstanceRequest) ProtoMessage() {}

func (x *NodeCheckpointAgentInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_node_rpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeCheckpointAgentInstanceRequest.ProtoReflect.Descriptor instead.
func (*NodeCheckpointAgentInstanceRequest) Descriptor() ([]byte, []int) {
	return file_goblin_v1_node_rpc_proto_rawDescGZIP(), []int{6}
}

func (x *NodeCheckpointAgentInstanceRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *NodeCheckpointAgentInstanceRequest) GetInstanceUuid() []byte {
	if x != nil {
		return x.InstanceUuid
	}
	return nil
}

func (x *NodeCheckpointAgentInstanceRequest) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

// NodeCheckpointAgentInstanceResponse reports the local image directory
// the dump landed in rather than a formatted sentence.
type NodeCheckpointAgentInstanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageDir      string                 `protobuf:"bytes,1,opt,name=image_dir,json=imageDir,proto3" json:"image_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeCheckpointAgentInstanceResponse) Reset() {
	*x = NodeCheckpointAgentInstanceResponse{}
	mi := &file_goblin_v1_node_rpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeCheckpointAgentInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeCheckpointAgentInstanceResponse) ProtoMessage() {}

func (x *NodeCheckpointAgentInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_node_rpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeCheckpointAgentInstanceResponse.ProtoReflect.Descriptor instead.
func (*NodeCheckpointAgentInstanceResponse) Descriptor() ([]byte, []int) {
	return file_goblin_v1_node_rpc_proto_rawDescGZIP(), []int{7}
}

func (x *NodeCheckpointAgentInstanceResponse) GetImageDir() string {
	if x != nil {
		return x.ImageDir
	}
	return ""
}

// NodeRestoreAgentInstanceRequest asks a node to restore an instance
// from an image already present in its own store. spec is required:
// a fresh registration (the destination side of a migration) has no
// other way to learn the agent type to instantiate.
type NodeRestoreAgentInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	InstanceUuid  []byte                 `protobuf:"bytes,2,opt,name=instance_uuid,json=instanceUuid,proto3" json:"instance_uuid,omitempty"`
	Epoch         uint64                 `protobuf:"varint,3,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Spec          *AgentSpec             `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeRestoreAgentInstanceRequest) Reset() {
	*x = NodeRestoreAgentInstanceRequest{}
	mi := &file_goblin_v1_node_rpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeRestoreAgentInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeRestoreAgentInstanceRequest) ProtoMessage() {}

func (x *NodeRestoreAgentInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_node_rpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeRestoreAgentInstanceRequest.ProtoReflect.Descriptor instead.
func (*NodeRestoreAgentInstanceRequest) Descriptor() ([]byte, []int) {
	return file_goblin_v1_node_rpc_proto_rawDescGZIP(), []int{8}
}

func (x *NodeRestoreAgentInstanceRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *NodeRestoreAgentInstanceRequest) GetInstanceUuid() []byte {
	if x != nil {
		return x.InstanceUuid
	}
	return nil
}

func (x *NodeRestoreAgentInstanceRequest) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *NodeRestoreAgentInstanceRequest) GetSpec() *AgentSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

// NodeRestoreAgentInstanceResponse reports the instance that was
// restored rather than a formatted sentence.
type NodeRestoreAgentInstanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeRestoreAgentInstanceResponse) Reset() {
	*x = NodeRestoreAgentInstanceResponse{}
	mi := &file_goblin_v1_node_rpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeRestoreAgentInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeRestoreAgentInstanceResponse) ProtoMessage() {}

func (x *NodeRestoreAgentInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_node_rpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeRestoreAgentInstanceResponse.ProtoReflect.Descriptor instead.
func (*NodeRestoreAgentInstanceResponse) Descriptor() ([]byte, []int) {
	return file_goblin_v1_node_rpc_proto_rawDescGZIP(), []int{9}
}

func (x *NodeRestoreAgentInstanceResponse) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

// NodePullCheckpointRequest asks a node to fetch an image from a peer.
// This is sent to the DESTINATION, which does the dialing - the
// coordinator runs on the leader, which is frequently neither end of
// the transfer, and routing bytes through it would put a
// multi-gigabyte stream on the node running consensus.
type NodePullCheckpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	InstanceUuid  []byte                 `protobuf:"bytes,2,opt,name=instance_uuid,json=instanceUuid,proto3" json:"instance_uuid,omitempty"`
	Epoch         uint64                 `protobuf:"varint,3,opt,name=epoch,proto3" json:"epoch,omitempty"`
	SourceAddr    string                 `protobuf:"bytes,4,opt,name=source_addr,json=sourceAddr,proto3" json:"source_addr,omitempty"`
	Token         []byte                 `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodePullCheckpointRequest) Reset() {
	*x = NodePullCheckpointRequest{}
	mi := &file_goblin_v1_node_rpc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodePullCheckpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodePullCheckpointRequest) ProtoMessage() {}

func (x *NodePullCheckpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_node_rpc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodePullCheckpointRequest.ProtoReflect.Descriptor instead.
func (*NodePullCheckpointRequest) Descriptor() ([]byte, []int) {
	return file_goblin_v1_node_rpc_proto_rawDescGZIP(), []int{10}
}

func (x *NodePullCheckpointRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *NodePullCheckpointRequest) GetInstanceUuid() []byte {
	if x != nil {
		return x.InstanceUuid
	}
	return nil
}

func (x *NodePullCheckpointRequest) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *NodePullCheckpointRequest) GetSourceAddr() string {
	if x != nil {
		return x.SourceAddr
	}
	return ""
}

func (x *NodePullCheckpointRequest) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

// NodePullCheckpointResponse reports the local image directory the
// pull landed in rather than a formatted sentence.
type NodePullCheckpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageDir      string                 `protobuf:"bytes,1,opt,name=image_dir,json=imageDir,proto3" json:"image_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodePullCheckpointResponse) Reset() {
	*x = NodePullCheckpointResponse{}
	mi := &file_goblin_v1_node_rpc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodePullCheckpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodePullCheckpointResponse) ProtoMessage() {}

func (x *NodePullCheckpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_node_rpc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodePullCheckpointResponse.ProtoReflect.Descriptor instead.
func (*NodePullCheckpointResponse) Descriptor() ([]byte, []int) {
	return file_goblin_v1_node_rpc_proto_rawDescGZIP(), []int{11}
}

func (x *NodePullCheckpointResponse) GetImageDir() string {
	if x != nil {
		return x.ImageDir
	}
	return ""
}

// NodeMigrationReadyRequest asks a prospective DESTINATION whether it
// can accept a migration, before the source is stopped.
//
// GOBLIN-DIV-048: the coordinator used to find out at the pull, which is
// step three - after the checkpoint has already killed the source
// process. A destination that had joined gossip but not yet applied any
// raft entry refused the pull, and the instance had to be rolled back
// from its image. Serf membership is not consensus membership, and the
// scheduler treated them as the same thing.
//
// The probe is sound rather than a narrower race because the predicate
// is MONOTONIC: the operator key registry is seeded once and the FSM
// refuses to remove the last key, so a destination that reports ready
// cannot become unready before the pull.
type NodeMigrationReadyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// instance_id is carried for logging only; readiness is a property of
	// the node, not of the instance being moved.
	InstanceId    string `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeMigrationReadyRequest) Reset() {
	*x = NodeMigrationReadyRequest{}
	mi := &file_goblin_v1_node_rpc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeMigrationReadyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeMigrationReadyRequest) ProtoMessage() {}

func (x *NodeMigrationReadyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_node_rpc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeMigrationReadyRequest.ProtoReflect.Descriptor instead.
func (*NodeMigrationReadyRequest) Descriptor() ([]byte, []int) {
	return file_goblin_v1_node_rpc_proto_rawDescGZIP(), []int{12}
}

func (x *NodeMigrationReadyRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

// NodeMigrationReadyResponse reports the destination's own view of
// itself. The fields are the ones GOBLIN-DIV-048 needed to tell "not
// caught up" from "genuinely absent", so a refusal explains itself
// instead of being reduced to a boolean.
type NodeMigrationReadyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Ready bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	// reason is empty when ready; otherwise it names what is missing.
	Reason         string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	RegistrySerial uint64 `protobuf:"varint,3,opt,name=registry_serial,json=registrySerial,proto3" json:"registry_serial,omitempty"`
	AppliedIndex   uint64 `protobuf:"varint,4,opt,name=applied_index,json=appliedIndex,proto3" json:"applied_index,omitempty"`
	CommitIndex    uint64 `protobuf:"varint,5,opt,name=commit_index,json=commitIndex,proto3" json:"commit_index,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NodeMigrationReadyResponse) Reset() {
	*x = NodeMigrationReadyResponse{}
	mi := &file_goblin_v1_node_rpc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeMigrationReadyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeMigrationReadyResponse) ProtoMessage() {}

func (x *NodeMigrationReadyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_node_rpc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeMigrationReadyResponse.ProtoReflect.Descriptor instead.
func (*NodeMigrationReadyResponse) Descriptor() ([]byte, []int) {
	return file_goblin_v1_node_rpc_proto_rawDescGZIP(), []int{13}
}

func (x *NodeMigrationReadyResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *NodeMigrationReadyResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *NodeMigrationReadyResponse) GetRegistrySerial() uint64 {
	if x != nil {
		return x.RegistrySerial
	}
	return 0
}

func (x *NodeMigrationReadyResponse) GetAppliedIndex() uint64 {
	if x != nil {
		return x.AppliedIndex
	}
	return 0
}

func (x *NodeMigrationReadyResponse) GetCommitIndex() uint64 {
	if x != nil {
		return x.CommitIndex
	}
	return 0
}

var File_goblin_v1_node_rpc_proto protoreflect.FileDescriptor

const file_goblin_v1_node_rpc_proto_rawDesc = "" +
	"\n" +
	"\x18goblin/v1/node_rpc.proto\x12\tgoblin.v1\x1a\x19goblin/v1/scheduler.proto\"j\n" +
	"\x1dNodeStartAgentInstanceRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12(\n" +
	"\x04spec\x18\x02 \x01(\v2\x14.goblin.v1.AgentSpecR\x04spec\"A\n" +
	"\x1eNodeStartAgentInstanceResponse\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\"?\n" +
	"\x1cNodeStopAgentInstanceRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\"i\n" +
	"\x1dNodeStopAgentInstanceResponse\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12'\n" +
	"\x0falready_stopped\x18\x02 \x01(\bR\x0ealreadyStopped\"Y\n" +
	"\x1eNodeSignalAgentInstanceRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x16\n" +
	"\x06signum\x18\x02 \x01(\x05R\x06signum\"Z\n" +
	"\x1fNodeSignalAgentInstanceResponse\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x16\n" +
	"\x06signum\x18\x02 \x01(\x05R\x06signum\"\x80\x01\n" +
	"\"NodeCheckpointAgentInstanceRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12#\n" +
	"\rinstance_uuid\x18\x02 \x01(\fR\finstanceUuid\x12\x14\n" +
	"\x05epoch\x18\x03 \x01(\x04R\x05epoch\"B\n" +
	"#NodeCheckpointAgentInstanceResponse\x12\x1b\n" +
	"\timage_dir\x18\x01 \x01(\tR\bimageDir\"\xa7\x01\n" +
	"\x1fNodeRestoreAgentInstanceRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12#\n" +
	"\rinstance_uuid\x18\x02 \x01(\fR\finstanceUuid\x12\x14\n" +
	"\x05epoch\x18\x03 \x01(\x04R\x05epoch\x12(\n" +
	"\x04spec\x18\x04 \x01(\v2\x14.goblin.v1.AgentSpecR\x04spec\"C\n" +
	" NodeRestoreAgentInstanceResponse\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\"\xae\x01\n" +
	"\x19NodePullCheckpointRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12#\n" +
	"\rinstance_uuid\x18\x02 \x01(\fR\finstanceUuid\x12\x14\n" +
	"\x05epoch\x18\x03 \x01(\x04R\x05epoch\x12\x1f\n" +
	"\vsource_addr\x18\x04 \x01(\tR\n" +
	"sourceAddr\x12\x14\n" +
	"\x05token\x18\x05 \x01(\fR\x05token\"9\n" +
	"\x1aNodePullCheckpointResponse\x12\x1b\n" +
	"\timage_dir\x18\x01 \x01(\tR\bimageDir\"<\n" +
	"\x19NodeMigrationReadyRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\"\xbb\x01\n" +
	"\x1aNodeMigrationReadyResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12'\n" +
	"\x0fregistry_serial\x18\x03 \x01(\x04R\x0eregistrySerial\x12#\n" +
	"\rapplied_index\x18\x04 \x01(\x04R\fappliedIndex\x12!\n" +
	"\fcommit_index\x18\x05 \x01(\x04R\vcommitIndexB+Z)github.com/goppydae/goblin/proto;goblinv1b\x06proto3"

var (
	file_goblin_v1_node_rpc_proto_rawDescOnce sync.Once
	file_goblin_v1_node_rpc_proto_rawDescData []byte
)

func file_goblin_v1_node_rpc_proto_rawDescGZIP() []byte {
	file_goblin_v1_node_rpc_proto_rawDescOnce.Do(func() {
		file_goblin_v1_node_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_goblin_v1_node_rpc_proto_rawDesc), len(file_goblin_v1_node_rpc_proto_rawDesc)))
	})
	return file_goblin_v1_node_rpc_proto_rawDescData
}

var file_goblin_v1_node_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_goblin_v1_node_rpc_proto_goTypes = []any{
	(*NodeStartAgentInstanceRequest)(nil),       // 0: goblin.v1.NodeStartAgentInstanceRequest
	(*NodeStartAgentInstanceResponse)(nil),      // 1: goblin.v1.NodeStartAgentInstanceResponse
	(*NodeStopAgentInstanceRequest)(nil),        // 2: goblin.v1.NodeStopAgentInstanceRequest
	(*NodeStopAgentInstanceResponse)(nil),       // 3: goblin.v1.NodeStopAgentInstanceResponse
	(*NodeSignalAgentInstanceRequest)(nil),      // 4: goblin.v1.NodeSignalAgentInstanceRequest
	(*NodeSignalAgentInstanceResponse)(nil),     // 5: goblin.v1.NodeSignalAgentInstanceResponse
	(*NodeCheckpointAgentInstanceRequest)(nil),  // 6: goblin.v1.NodeCheckpointAgentInstanceRequest
	(*NodeCheckpointAgentInstanceResponse)(nil), // 7: goblin.v1.NodeCheckpointAgentInstanceResponse
	(*NodeRestoreAgentInstanceRequest)(nil),     // 8: goblin.v1.NodeRestoreAgentInstanceRequest
	(*NodeRestoreAgentInstanceResponse)(nil),    // 9: goblin.v1.NodeRestoreAgentInstanceResponse
	(*NodePullCheckpointRequest)(nil),           // 10: goblin.v1.NodePullCheckpointRequest
	(*NodePullCheckpointResponse)(nil),          // 11: goblin.v1.NodePullCheckpointResponse
	(*NodeMigrationReadyRequest)(nil),           // 12: goblin.v1.NodeMigrationReadyRequest
	(*NodeMigrationReadyResponse)(nil),          // 13: goblin.v1.NodeMigrationReadyResponse
	(*AgentSpec)(nil),                           // 14: goblin.v1.AgentSpec
}
var file_goblin_v1_node_rpc_proto_depIdxs = []int32{
	14, // 0: goblin.v1.NodeStartAgentInstanceRequest.spec:type_name -> goblin.v1.AgentSpec
	14, // 1: goblin.v1.NodeRestoreAgentInstanceRequest.spec:type_name -> goblin.v1.AgentSpec
	2,  // [2:2] is the sub-list for method output_type
	2,  // [2:2] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_goblin_v1_node_rpc_proto_init() }
func file_goblin_v1_node_rpc_proto_init() {
	if File_goblin_v1_node_rpc_proto != nil {
		return
	}
	file_goblin_v1_scheduler_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_goblin_v1_node_rpc_proto_rawDesc), len(file_goblin_v1_node_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_goblin_v1_node_rpc_proto_goTypes,
		DependencyIndexes: file_goblin_v1_node_rpc_proto_depIdxs,
		MessageInfos:      file_goblin_v1_node_rpc_proto_msgTypes,
	}.Build()
	File_goblin_v1_node_rpc_proto = out.File
	file_goblin_v1_node_rpc_proto_goTypes = nil
	file_goblin_v1_node_rpc_proto_depIdxs = nil
}
