// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: goblin/v1/rpc.proto

package goblinv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Stream type enum
type StreamType int32

const (
	StreamType_STREAM_TYPE_UNSPECIFIED  StreamType = 0
	StreamType_STREAM_TYPE_RPC_REQUEST  StreamType = 1
	StreamType_STREAM_TYPE_RPC_RESPONSE StreamType = 2
	StreamType_STREAM_TYPE_EVENT_STREAM StreamType = 3
)

// Enum value maps for StreamType.
var (
	StreamType_name = map[int32]string{
		0: "STREAM_TYPE_UNSPECIFIED",
		1: "STREAM_TYPE_RPC_REQUEST",
		2: "STREAM_TYPE_RPC_RESPONSE",
		3: "STREAM_TYPE_EVENT_STREAM",
	}
	StreamType_value = map[string]int32{
		"STREAM_TYPE_UNSPECIFIED":  0,
		"STREAM_TYPE_RPC_REQUEST":  1,
		"STREAM_TYPE_RPC_RESPONSE": 2,
		"STREAM_TYPE_EVENT_STREAM": 3,
	}
)

func (x StreamType) Enum() *StreamType {
	p := new(StreamType)
	*p = x
	return p
}

func (x StreamType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamType) Descriptor() protoreflect.EnumDescriptor {
	return file_goblin_v1_rpc_proto_enumTypes[0].Descriptor()
}

func (StreamType) Type() protoreflect.EnumType {
	return &file_goblin_v1_rpc_proto_enumTypes[0]
}

func (x StreamType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamType.Descriptor instead.
func (StreamType) EnumDescriptor() ([]byte, []int) {
	return file_goblin_v1_rpc_proto_rawDescGZIP(), []int{0}
}

// RPC Request message
type RPCRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint32                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`   // e.g. "SchedulerRPC.ListJobs"
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"` // Protobuf-encoded request
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RPCRequest) Reset() {
	*x = RPCRequest{}
	mi := &file_goblin_v1_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCRequest) ProtoMessage() {}

func (x *RPCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCRequest.ProtoReflect.Descriptor instead.
func (*RPCRequest) Descriptor() ([]byte, []int) {
	return file_goblin_v1_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *RPCRequest) GetRequestId() uint32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *RPCRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RPCRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// RPC Response message
type RPCResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint32                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"` // Protobuf-encoded response or error message
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`     // Error message if success=false
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RPCResponse) Reset() {
	*x = RPCResponse{}
	mi := &file_goblin_v1_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCResponse) ProtoMessage() {}

func (x *RPCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCResponse.ProtoReflect.Descriptor instead.
func (*RPCResponse) Descriptor() ([]byte, []int) {
	return file_goblin_v1_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *RPCResponse) GetRequestId() uint32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *RPCResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RPCResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RPCResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_goblin_v1_rpc_proto protoreflect.FileDescriptor

const file_goblin_v1_rpc_proto_rawDesc = "" +
	"\n" +
	"\x13goblin/v1/rpc.proto\x12\tgoblin.v1\"]\n" +
	"\n" +
	"RPCRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\rR\trequestId\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"v\n" +
	"\vRPCResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\rR\trequestId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error*\x82\x01\n" +
	"\n" +
	"StreamType\x12\x1b\n" +
	"\x17STREAM_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17STREAM_TYPE_RPC_REQUEST\x10\x01\x12\x1c\n" +
	"\x18STREAM_TYPE_RPC_RESPONSE\x10\x02\x12\x1c\n" +
	"\x18STREAM_TYPE_EVENT_STREAM\x10\x03B+Z)github.com/goppydae/goblin/proto;goblinv1b\x06proto3"

var (
	file_goblin_v1_rpc_proto_rawDescOnce sync.Once
	file_goblin_v1_rpc_proto_rawDescData []byte
)

func file_goblin_v1_rpc_proto_rawDescGZIP() []byte {
	file_goblin_v1_rpc_proto_rawDescOnce.Do(func() {
		file_goblin_v1_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_goblin_v1_rpc_proto_rawDesc), len(file_goblin_v1_rpc_proto_rawDesc)))
	})
	return file_goblin_v1_rpc_proto_rawDescData
}

var file_goblin_v1_rpc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_goblin_v1_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_goblin_v1_rpc_proto_goTypes = []any{
	(StreamType)(0),     // 0: goblin.v1.StreamType
	(*RPCRequest)(nil),  // 1: goblin.v1.RPCRequest
	(*RPCResponse)(nil), // 2: goblin.v1.RPCResponse
}
var file_goblin_v1_rpc_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_goblin_v1_rpc_proto_init() }
func file_goblin_v1_rpc_proto_init() {
	if File_goblin_v1_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_goblin_v1_rpc_proto_rawDesc), len(file_goblin_v1_rpc_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_goblin_v1_rpc_proto_goTypes,
		DependencyIndexes: file_goblin_v1_rpc_proto_depIdxs,
		EnumInfos:         file_goblin_v1_rpc_proto_enumTypes,
		MessageInfos:      file_goblin_v1_rpc_proto_msgTypes,
	}.Build()
	File_goblin_v1_rpc_proto = out.File
	file_goblin_v1_rpc_proto_goTypes = nil
	file_goblin_v1_rpc_proto_depIdxs = nil
}
