// Copyright (c) 2025 Steven Verhelle (enqack)
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
//
// SPDX-License-Identifier: MPL-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: goblin/v1/scheduler_rpc.proto

package goblinv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ScaleAgentRequest changes the desired replica count for one spec.
// agent_id accepts either the spec UUID or the operator-facing name,
// matching what the CLI already passes.
type ScaleAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Replicas      int32                  `protobuf:"varint,2,opt,name=replicas,proto3" json:"replicas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScaleAgentRequest) Reset() {
	*x = ScaleAgentRequest{}
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScaleAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScaleAgentRequest) ProtoMessage() {}

func (x *ScaleAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScaleAgentRequest.ProtoReflect.Descriptor instead.
func (*ScaleAgentRequest) Descriptor() ([]byte, []int) {
	return file_goblin_v1_scheduler_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *ScaleAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ScaleAgentRequest) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

// ScaleAgentResponse reports applied state rather than a formatted
// sentence. The previous response was a string built with fmt.Sprintf,
// which a caller could only display, never assert on.
type ScaleAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpecUuid      []byte                 `protobuf:"bytes,1,opt,name=spec_uuid,json=specUuid,proto3" json:"spec_uuid,omitempty"` // 16-byte UUIDv7 of the scaled spec
	Replicas      int32                  `protobuf:"varint,2,opt,name=replicas,proto3" json:"replicas,omitempty"`                // replica count now recorded
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScaleAgentResponse) Reset() {
	*x = ScaleAgentResponse{}
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScaleAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScaleAgentResponse) ProtoMessage() {}

func (x *ScaleAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScaleAgentResponse.ProtoReflect.Descriptor instead.
func (*ScaleAgentResponse) Descriptor() ([]byte, []int) {
	return file_goblin_v1_scheduler_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *ScaleAgentResponse) GetSpecUuid() []byte {
	if x != nil {
		return x.SpecUuid
	}
	return nil
}

func (x *ScaleAgentResponse) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

// ListJobsRequest is empty so fields can be added later without a
// signature change (e.g. a status filter).
type ListJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsRequest) Reset() {
	*x = ListJobsRequest{}
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsRequest) ProtoMessage() {}

func (x *ListJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsRequest.ProtoReflect.Descriptor instead.
func (*ListJobsRequest) Descriptor() ([]byte, []int) {
	return file_goblin_v1_scheduler_rpc_proto_rawDescGZIP(), []int{2}
}

// JobInfo is the RPC-facing view of a scheduled job; assembled from the
// job assignment and spec keys at request time rather than stored as
// its own record.
type JobInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	AssignedNode  string                 `protobuf:"bytes,2,opt,name=assigned_node,json=assignedNode,proto3" json:"assigned_node,omitempty"`
	AgentType     string                 `protobuf:"bytes,3,opt,name=agent_type,json=agentType,proto3" json:"agent_type,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobInfo) Reset() {
	*x = JobInfo{}
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobInfo) ProtoMessage() {}

func (x *JobInfo) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobInfo.ProtoReflect.Descriptor instead.
func (*JobInfo) Descriptor() ([]byte, []int) {
	return file_goblin_v1_scheduler_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *JobInfo) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobInfo) GetAssignedNode() string {
	if x != nil {
		return x.AssignedNode
	}
	return ""
}

func (x *JobInfo) GetAgentType() string {
	if x != nil {
		return x.AgentType
	}
	return ""
}

func (x *JobInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*JobInfo             `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsResponse) Reset() {
	*x = ListJobsResponse{}
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsResponse) ProtoMessage() {}

func (x *ListJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsResponse.ProtoReflect.Descriptor instead.
func (*ListJobsResponse) Descriptor() ([]byte, []int) {
	return file_goblin_v1_scheduler_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *ListJobsResponse) GetJobs() []*JobInfo {
	if x != nil {
		return x.Jobs
	}
	return nil
}

// MembersRequest is empty so fields can be added later without a
// signature change.
type MembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MembersRequest) Reset() {
	*x = MembersRequest{}
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MembersRequest) ProtoMessage() {}

func (x *MembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MembersRequest.ProtoReflect.Descriptor instead.
func (*MembersRequest) Descriptor() ([]byte, []int) {
	return file_goblin_v1_scheduler_rpc_proto_rawDescGZIP(), []int{5}
}

// MemberInfo is the RPC-facing view of a Serf cluster member.
type MemberInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Tags          map[string]string      `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Leader        bool                   `protobuf:"varint,5,opt,name=leader,proto3" json:"leader,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberInfo) Reset() {
	*x = MemberInfo{}
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberInfo) ProtoMessage() {}

func (x *MemberInfo) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberInfo.ProtoReflect.Descriptor instead.
func (*MemberInfo) Descriptor() ([]byte, []int) {
	return file_goblin_v1_scheduler_rpc_proto_rawDescGZIP(), []int{6}
}

func (x *MemberInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MemberInfo) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *MemberInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MemberInfo) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *MemberInfo) GetLeader() bool {
	if x != nil {
		return x.Leader
	}
	return false
}

type MembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*MemberInfo          `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MembersResponse) Reset() {
	*x = MembersResponse{}
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MembersResponse) ProtoMessage() {}

func (x *MembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MembersResponse.ProtoReflect.Descriptor instead.
func (*MembersResponse) Descriptor() ([]byte, []int) {
	return file_goblin_v1_scheduler_rpc_proto_rawDescGZIP(), []int{7}
}

func (x *MembersResponse) GetMembers() []*MemberInfo {
	if x != nil {
		return x.Members
	}
	return nil
}

// ListGlobalAgentsRequest is empty so fields can be added later without
// a signature change (e.g. a name filter).
type ListGlobalAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGlobalAgentsRequest) Reset() {
	*x = ListGlobalAgentsRequest{}
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGlobalAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGlobalAgentsRequest) ProtoMessage() {}

func (x *ListGlobalAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGlobalAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListGlobalAgentsRequest) Descriptor() ([]byte, []int) {
	return file_goblin_v1_scheduler_rpc_proto_rawDescGZIP(), []int{8}
}

type ListGlobalAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*AgentSpec           `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGlobalAgentsResponse) Reset() {
	*x = ListGlobalAgentsResponse{}
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGlobalAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGlobalAgentsResponse) ProtoMessage() {}

func (x *ListGlobalAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGlobalAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListGlobalAgentsResponse) Descriptor() ([]byte, []int) {
	return file_goblin_v1_scheduler_rpc_proto_rawDescGZIP(), []int{9}
}

func (x *ListGlobalAgentsResponse) GetAgents() []*AgentSpec {
	if x != nil {
		return x.Agents
	}
	return nil
}

// ListLocalAgentsRequest is empty so fields can be added later without
// a signature change.
type ListLocalAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLocalAgentsRequest) Reset() {
	*x = ListLocalAgentsRequest{}
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLocalAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLocalAgentsRequest) ProtoMessage() {}

func (x *ListLocalAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLocalAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListLocalAgentsRequest) Descriptor() ([]byte, []int) {
	return file_goblin_v1_scheduler_rpc_proto_rawDescGZIP(), []int{10}
}

// LocalAgentInfo is the RPC-facing view of an agent managed by the
// local GAPI agent manager (not a scheduled global agent instance).
type LocalAgentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Language      string                 `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	UptimeNs      int64                  `protobuf:"varint,5,opt,name=uptime_ns,json=uptimeNs,proto3" json:"uptime_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalAgentInfo) Reset() {
	*x = LocalAgentInfo{}
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalAgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalAgentInfo) ProtoMessage() {}

func (x *LocalAgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalAgentInfo.ProtoReflect.Descriptor instead.
func (*LocalAgentInfo) Descriptor() ([]byte, []int) {
	return file_goblin_v1_scheduler_rpc_proto_rawDescGZIP(), []int{11}
}

func (x *LocalAgentInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LocalAgentInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LocalAgentInfo) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *LocalAgentInfo) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *LocalAgentInfo) GetUptimeNs() int64 {
	if x != nil {
		return x.UptimeNs
	}
	return 0
}

type ListLocalAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*LocalAgentInfo      `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLocalAgentsResponse) Reset() {
	*x = ListLocalAgentsResponse{}
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLocalAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLocalAgentsResponse) ProtoMessage() {}

func (x *ListLocalAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLocalAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListLocalAgentsResponse) Descriptor() ([]byte, []int) {
	return file_goblin_v1_scheduler_rpc_proto_rawDescGZIP(), []int{12}
}

func (x *ListLocalAgentsResponse) GetAgents() []*LocalAgentInfo {
	if x != nil {
		return x.Agents
	}
	return nil
}

// GetGlobalAgentRequest identifies one spec. agent_id accepts either
// the spec UUID or the operator-facing name.
type GetGlobalAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGlobalAgentRequest) Reset() {
	*x = GetGlobalAgentRequest{}
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGlobalAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGlobalAgentRequest) ProtoMessage() {}

func (x *GetGlobalAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGlobalAgentRequest.ProtoReflect.Descriptor instead.
func (*GetGlobalAgentRequest) Descriptor() ([]byte, []int) {
	return file_goblin_v1_scheduler_rpc_proto_rawDescGZIP(), []int{13}
}

func (x *GetGlobalAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type GetGlobalAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          *AgentSpec             `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGlobalAgentResponse) Reset() {
	*x = GetGlobalAgentResponse{}
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGlobalAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGlobalAgentResponse) ProtoMessage() {}

func (x *GetGlobalAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGlobalAgentResponse.ProtoReflect.Descriptor instead.
func (*GetGlobalAgentResponse) Descriptor() ([]byte, []int) {
	return file_goblin_v1_scheduler_rpc_proto_rawDescGZIP(), []int{14}
}

func (x *GetGlobalAgentResponse) GetSpec() *AgentSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

// GetEventsRequest asks for events with index greater than cursor.
type GetEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        uint64                 `protobuf:"varint,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsRequest) Reset() {
	*x = GetEventsRequest{}
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsRequest) ProtoMessage() {}

func (x *GetEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsRequest.ProtoReflect.Descriptor instead.
func (*GetEventsRequest) Descriptor() ([]byte, []int) {
	return file_goblin_v1_scheduler_rpc_proto_rawDescGZIP(), []int{15}
}

func (x *GetEventsRequest) GetCursor() uint64 {
	if x != nil {
		return x.Cursor
	}
	return 0
}

// LogEvent is one entry in the in-memory supervisor event log.
type LogEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint64                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEvent) Reset() {
	*x = LogEvent{}
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEvent) ProtoMessage() {}

func (x *LogEvent) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEvent.ProtoReflect.Descriptor instead.
func (*LogEvent) Descriptor() ([]byte, []int) {
	return file_goblin_v1_scheduler_rpc_proto_rawDescGZIP(), []int{16}
}

func (x *LogEvent) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *LogEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LogEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*LogEvent            `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsResponse) Reset() {
	*x = GetEventsResponse{}
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsResponse) ProtoMessage() {}

func (x *GetEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsResponse.ProtoReflect.Descriptor instead.
func (*GetEventsResponse) Descriptor() ([]byte, []int) {
	return file_goblin_v1_scheduler_rpc_proto_rawDescGZIP(), []int{17}
}

func (x *GetEventsResponse) GetEvents() []*LogEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

// ListAgentInstancesRequest filters instance listing; empty spec_id
// returns every instance. spec_id accepts either the canonical spec
// UUID or the operator-facing name.
type ListAgentInstancesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpecId        string                 `protobuf:"bytes,1,opt,name=spec_id,json=specId,proto3" json:"spec_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentInstancesRequest) Reset() {
	*x = ListAgentInstancesRequest{}
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentInstancesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentInstancesRequest) ProtoMessage() {}

func (x *ListAgentInstancesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentInstancesRequest.ProtoReflect.Descriptor instead.
func (*ListAgentInstancesRequest) Descriptor() ([]byte, []int) {
	return file_goblin_v1_scheduler_rpc_proto_rawDescGZIP(), []int{18}
}

func (x *ListAgentInstancesRequest) GetSpecId() string {
	if x != nil {
		return x.SpecId
	}
	return ""
}

type ListAgentInstancesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instances     []*AgentInstance       `protobuf:"bytes,1,rep,name=instances,proto3" json:"instances,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentInstancesResponse) Reset() {
	*x = ListAgentInstancesResponse{}
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentInstancesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentInstancesResponse) ProtoMessage() {}

func (x *ListAgentInstancesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentInstancesResponse.ProtoReflect.Descriptor instead.
func (*ListAgentInstancesResponse) Descriptor() ([]byte, []int) {
	return file_goblin_v1_scheduler_rpc_proto_rawDescGZIP(), []int{19}
}

func (x *ListAgentInstancesResponse) GetInstances() []*AgentInstance {
	if x != nil {
		return x.Instances
	}
	return nil
}

// RegisterGlobalAgentRequest registers or updates a global agent spec.
// spec.spec_uuid is server-owned: RegisterAgent mints it from spec.name
// when unset. A caller-supplied spec_uuid is rejected, not overwritten
// (see goblin-typed-rpc-design.md, "Server-owned fields must be
// rejected, not overwritten").
type RegisterGlobalAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          *AgentSpec             `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterGlobalAgentRequest) Reset() {
	*x = RegisterGlobalAgentRequest{}
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterGlobalAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterGlobalAgentRequest) ProtoMessage() {}

func (x *RegisterGlobalAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterGlobalAgentRequest.ProtoReflect.Descriptor instead.
func (*RegisterGlobalAgentRequest) Descriptor() ([]byte, []int) {
	return file_goblin_v1_scheduler_rpc_proto_rawDescGZIP(), []int{20}
}

func (x *RegisterGlobalAgentRequest) GetSpec() *AgentSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

// RegisterGlobalAgentResponse reports the identity assigned to the
// spec rather than a formatted sentence.
type RegisterGlobalAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpecUuid      []byte                 `protobuf:"bytes,1,opt,name=spec_uuid,json=specUuid,proto3" json:"spec_uuid,omitempty"` // spec UUID minted (or confirmed) at registration
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterGlobalAgentResponse) Reset() {
	*x = RegisterGlobalAgentResponse{}
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterGlobalAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterGlobalAgentResponse) ProtoMessage() {}

func (x *RegisterGlobalAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterGlobalAgentResponse.ProtoReflect.Descriptor instead.
func (*RegisterGlobalAgentResponse) Descriptor() ([]byte, []int) {
	return file_goblin_v1_scheduler_rpc_proto_rawDescGZIP(), []int{21}
}

func (x *RegisterGlobalAgentResponse) GetSpecUuid() []byte {
	if x != nil {
		return x.SpecUuid
	}
	return nil
}

func (x *RegisterGlobalAgentResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// DeleteGlobalAgentRequest identifies the spec to delete. agent_id
// accepts either the spec UUID or the operator-facing name.
type DeleteGlobalAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGlobalAgentRequest) Reset() {
	*x = DeleteGlobalAgentRequest{}
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGlobalAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGlobalAgentRequest) ProtoMessage() {}

func (x *DeleteGlobalAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGlobalAgentRequest.ProtoReflect.Descriptor instead.
func (*DeleteGlobalAgentRequest) Descriptor() ([]byte, []int) {
	return file_goblin_v1_scheduler_rpc_proto_rawDescGZIP(), []int{22}
}

func (x *DeleteGlobalAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

// DeleteGlobalAgentResponse reports the identity of the spec that was
// deleted rather than a formatted sentence.
type DeleteGlobalAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpecUuid      []byte                 `protobuf:"bytes,1,opt,name=spec_uuid,json=specUuid,proto3" json:"spec_uuid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGlobalAgentResponse) Reset() {
	*x = DeleteGlobalAgentResponse{}
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGlobalAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGlobalAgentResponse) ProtoMessage() {}

func (x *DeleteGlobalAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGlobalAgentResponse.ProtoReflect.Descriptor instead.
func (*DeleteGlobalAgentResponse) Descriptor() ([]byte, []int) {
	return file_goblin_v1_scheduler_rpc_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteGlobalAgentResponse) GetSpecUuid() []byte {
	if x != nil {
		return x.SpecUuid
	}
	return nil
}

func (x *DeleteGlobalAgentResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Job is the RPC-facing view of a job submission - a faithful,
// field-for-field translation of core/scheduler.Job. That type predates
// protobuf and stays a plain Go struct (its storage encoding is JSON in
// the KV store); this message is only the wire shape for SubmitJob.
type Job struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AgentId       string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentType     string                 `protobuf:"bytes,3,opt,name=agent_type,json=agentType,proto3" json:"agent_type,omitempty"`
	AssignedNode  string                 `protobuf:"bytes,4,opt,name=assigned_node,json=assignedNode,proto3" json:"assigned_node,omitempty"`
	Resources     *ResourceReq           `protobuf:"bytes,5,opt,name=resources,proto3" json:"resources,omitempty"`
	Constraints   map[string]string      `protobuf:"bytes,6,rep,name=constraints,proto3" json:"constraints,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Requirements  map[string]string      `protobuf:"bytes,7,rep,name=requirements,proto3" json:"requirements,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RestartPolicy string                 `protobuf:"bytes,8,opt,name=restart_policy,json=restartPolicy,proto3" json:"restart_policy,omitempty"` // "always", "on-failure", "never"
	Env           map[string]string      `protobuf:"bytes,9,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_goblin_v1_scheduler_rpc_proto_rawDescGZIP(), []int{24}
}

func (x *Job) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Job) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Job) GetAgentType() string {
	if x != nil {
		return x.AgentType
	}
	return ""
}

func (x *Job) GetAssignedNode() string {
	if x != nil {
		return x.AssignedNode
	}
	return ""
}

func (x *Job) GetResources() *ResourceReq {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *Job) GetConstraints() map[string]string {
	if x != nil {
		return x.Constraints
	}
	return nil
}

func (x *Job) GetRequirements() map[string]string {
	if x != nil {
		return x.Requirements
	}
	return nil
}

func (x *Job) GetRestartPolicy() string {
	if x != nil {
		return x.RestartPolicy
	}
	return ""
}

func (x *Job) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

type SubmitJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *Job                   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitJobRequest) Reset() {
	*x = SubmitJobRequest{}
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobRequest) ProtoMessage() {}

func (x *SubmitJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobRequest.ProtoReflect.Descriptor instead.
func (*SubmitJobRequest) Descriptor() ([]byte, []int) {
	return file_goblin_v1_scheduler_rpc_proto_rawDescGZIP(), []int{25}
}

func (x *SubmitJobRequest) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

// SubmitJobResponse reports where the job landed rather than a
// formatted sentence.
type SubmitJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	AssignedNode  string                 `protobuf:"bytes,2,opt,name=assigned_node,json=assignedNode,proto3" json:"assigned_node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitJobResponse) Reset() {
	*x = SubmitJobResponse{}
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobResponse) ProtoMessage() {}

func (x *SubmitJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobResponse.ProtoReflect.Descriptor instead.
func (*SubmitJobResponse) Descriptor() ([]byte, []int) {
	return file_goblin_v1_scheduler_rpc_proto_rawDescGZIP(), []int{26}
}

func (x *SubmitJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *SubmitJobResponse) GetAssignedNode() string {
	if x != nil {
		return x.AssignedNode
	}
	return ""
}

// DrainNodeRequest names the node to evacuate.
type DrainNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrainNodeRequest) Reset() {
	*x = DrainNodeRequest{}
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainNodeRequest) ProtoMessage() {}

func (x *DrainNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainNodeRequest.ProtoReflect.Descriptor instead.
func (*DrainNodeRequest) Descriptor() ([]byte, []int) {
	return file_goblin_v1_scheduler_rpc_proto_rawDescGZIP(), []int{27}
}

func (x *DrainNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type DrainNodeResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MigratedJobIds []string               `protobuf:"bytes,1,rep,name=migrated_job_ids,json=migratedJobIds,proto3" json:"migrated_job_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DrainNodeResponse) Reset() {
	*x = DrainNodeResponse{}
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainNodeResponse) ProtoMessage() {}

func (x *DrainNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainNodeResponse.ProtoReflect.Descriptor instead.
func (*DrainNodeResponse) Descriptor() ([]byte, []int) {
	return file_goblin_v1_scheduler_rpc_proto_rawDescGZIP(), []int{28}
}

func (x *DrainNodeResponse) GetMigratedJobIds() []string {
	if x != nil {
		return x.MigratedJobIds
	}
	return nil
}

// PublishEventRequest forwards to membership (Serf) UserEvent. payload
// stays opaque bytes here; typing the event envelope itself is a
// separate piece of work (Serf events), not this one.
type PublishEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishEventRequest) Reset() {
	*x = PublishEventRequest{}
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishEventRequest) ProtoMessage() {}

func (x *PublishEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishEventRequest.ProtoReflect.Descriptor instead.
func (*PublishEventRequest) Descriptor() ([]byte, []int) {
	return file_goblin_v1_scheduler_rpc_proto_rawDescGZIP(), []int{29}
}

func (x *PublishEventRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PublishEventRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// PublishEventResponse confirms the topic that was published rather
// than a formatted sentence.
type PublishEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishEventResponse) Reset() {
	*x = PublishEventResponse{}
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishEventResponse) ProtoMessage() {}

func (x *PublishEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishEventResponse.ProtoReflect.Descriptor instead.
func (*PublishEventResponse) Descriptor() ([]byte, []int) {
	return file_goblin_v1_scheduler_rpc_proto_rawDescGZIP(), []int{30}
}

func (x *PublishEventResponse) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

// MigrateJobRequest reassigns a job to another node. Distinct from
// MigrateInstanceRequest: this stops work in one place and starts it
// in another, and the process does not survive the move.
type MigrateJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	ToNode        string                 `protobuf:"bytes,2,opt,name=to_node,json=toNode,proto3" json:"to_node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrateJobRequest) Reset() {
	*x = MigrateJobRequest{}
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrateJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrateJobRequest) ProtoMessage() {}

func (x *MigrateJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrateJobRequest.ProtoReflect.Descriptor instead.
func (*MigrateJobRequest) Descriptor() ([]byte, []int) {
	return file_goblin_v1_scheduler_rpc_proto_rawDescGZIP(), []int{31}
}

func (x *MigrateJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *MigrateJobRequest) GetToNode() string {
	if x != nil {
		return x.ToNode
	}
	return ""
}

// MigrateJobResponse reports the applied placement rather than a
// formatted sentence.
type MigrateJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	ToNode        string                 `protobuf:"bytes,2,opt,name=to_node,json=toNode,proto3" json:"to_node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrateJobResponse) Reset() {
	*x = MigrateJobResponse{}
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrateJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrateJobResponse) ProtoMessage() {}

func (x *MigrateJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrateJobResponse.ProtoReflect.Descriptor instead.
func (*MigrateJobResponse) Descriptor() ([]byte, []int) {
	return file_goblin_v1_scheduler_rpc_proto_rawDescGZIP(), []int{32}
}

func (x *MigrateJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *MigrateJobResponse) GetToNode() string {
	if x != nil {
		return x.ToNode
	}
	return ""
}

// MigrateInstanceRequest asks the leader to live-migrate one running
// instance to another node (GOBLIN-DIV-031). instance_id is the
// canonical UUID string, as goblinctl prints it - not the raw bytes
// spec_uuid/instance_uuid use elsewhere in this schema, since this is
// the field the CLI already passes as a string.
type MigrateInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	ToNode        string                 `protobuf:"bytes,2,opt,name=to_node,json=toNode,proto3" json:"to_node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrateInstanceRequest) Reset() {
	*x = MigrateInstanceRequest{}
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrateInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrateInstanceRequest) ProtoMessage() {}

func (x *MigrateInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrateInstanceRequest.ProtoReflect.Descriptor instead.
func (*MigrateInstanceRequest) Descriptor() ([]byte, []int) {
	return file_goblin_v1_scheduler_rpc_proto_rawDescGZIP(), []int{33}
}

func (x *MigrateInstanceRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *MigrateInstanceRequest) GetToNode() string {
	if x != nil {
		return x.ToNode
	}
	return ""
}

// MigrateInstanceResponse reports the instance's move rather than a
// formatted sentence.
type MigrateInstanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	FromNode      string                 `protobuf:"bytes,2,opt,name=from_node,json=fromNode,proto3" json:"from_node,omitempty"`
	ToNode        string                 `protobuf:"bytes,3,opt,name=to_node,json=toNode,proto3" json:"to_node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MigrateInstanceResponse) Reset() {
	*x = MigrateInstanceResponse{}
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MigrateInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MigrateInstanceResponse) ProtoMessage() {}

func (x *MigrateInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MigrateInstanceResponse.ProtoReflect.Descriptor instead.
func (*MigrateInstanceResponse) Descriptor() ([]byte, []int) {
	return file_goblin_v1_scheduler_rpc_proto_rawDescGZIP(), []int{34}
}

func (x *MigrateInstanceResponse) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *MigrateInstanceResponse) GetFromNode() string {
	if x != nil {
		return x.FromNode
	}
	return ""
}

func (x *MigrateInstanceResponse) GetToNode() string {
	if x != nil {
		return x.ToNode
	}
	return ""
}

// SignalAgentInstanceRequest asks the leader to signal an instance
// (GOBLIN-DIV-017, DDR-10). instance_id is the canonical UUID string,
// matching MigrateInstanceRequest.
type SignalAgentInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Signum        int32                  `protobuf:"varint,2,opt,name=signum,proto3" json:"signum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalAgentInstanceRequest) Reset() {
	*x = SignalAgentInstanceRequest{}
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalAgentInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalAgentInstanceRequest) ProtoMessage() {}

func (x *SignalAgentInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalAgentInstanceRequest.ProtoReflect.Descriptor instead.
func (*SignalAgentInstanceRequest) Descriptor() ([]byte, []int) {
	return file_goblin_v1_scheduler_rpc_proto_rawDescGZIP(), []int{35}
}

func (x *SignalAgentInstanceRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *SignalAgentInstanceRequest) GetSignum() int32 {
	if x != nil {
		return x.Signum
	}
	return 0
}

// SignalAgentInstanceResponse reports the authorized delivery rather
// than a formatted sentence.
type SignalAgentInstanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signum        int32                  `protobuf:"varint,1,opt,name=signum,proto3" json:"signum,omitempty"`
	InstanceId    string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalAgentInstanceResponse) Reset() {
	*x = SignalAgentInstanceResponse{}
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalAgentInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalAgentInstanceResponse) ProtoMessage() {}

func (x *SignalAgentInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalAgentInstanceResponse.ProtoReflect.Descriptor instead.
func (*SignalAgentInstanceResponse) Descriptor() ([]byte, []int) {
	return file_goblin_v1_scheduler_rpc_proto_rawDescGZIP(), []int{36}
}

func (x *SignalAgentInstanceResponse) GetSignum() int32 {
	if x != nil {
		return x.Signum
	}
	return 0
}

func (x *SignalAgentInstanceResponse) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *SignalAgentInstanceResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

var File_goblin_v1_scheduler_rpc_proto protoreflect.FileDescriptor

const file_goblin_v1_scheduler_rpc_proto_rawDesc = "" +
	"\n" +
	"\x1dgoblin/v1/scheduler_rpc.proto\x12\tgoblin.v1\x1a\x19goblin/v1/scheduler.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"J\n" +
	"\x11ScaleAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1a\n" +
	"\breplicas\x18\x02 \x01(\x05R\breplicas\"M\n" +
	"\x12ScaleAgentResponse\x12\x1b\n" +
	"\tspec_uuid\x18\x01 \x01(\fR\bspecUuid\x12\x1a\n" +
	"\breplicas\x18\x02 \x01(\x05R\breplicas\"\x11\n" +
	"\x0fListJobsRequest\"|\n" +
	"\aJobInfo\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12#\n" +
	"\rassigned_node\x18\x02 \x01(\tR\fassignedNode\x12\x1d\n" +
	"\n" +
	"agent_type\x18\x03 \x01(\tR\tagentType\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\":\n" +
	"\x10ListJobsResponse\x12&\n" +
	"\x04jobs\x18\x01 \x03(\v2\x12.goblin.v1.JobInfoR\x04jobs\"\x10\n" +
	"\x0eMembersRequest\"\xd2\x01\n" +
	"\n" +
	"MemberInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x123\n" +
	"\x04tags\x18\x04 \x03(\v2\x1f.goblin.v1.MemberInfo.TagsEntryR\x04tags\x12\x16\n" +
	"\x06leader\x18\x05 \x01(\bR\x06leader\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"B\n" +
	"\x0fMembersResponse\x12/\n" +
	"\amembers\x18\x01 \x03(\v2\x15.goblin.v1.MemberInfoR\amembers\"\x19\n" +
	"\x17ListGlobalAgentsRequest\"H\n" +
	"\x18ListGlobalAgentsResponse\x12,\n" +
	"\x06agents\x18\x01 \x03(\v2\x14.goblin.v1.AgentSpecR\x06agents\"\x18\n" +
	"\x16ListLocalAgentsRequest\"\x83\x01\n" +
	"\x0eLocalAgentInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x1a\n" +
	"\blanguage\x18\x04 \x01(\tR\blanguage\x12\x1b\n" +
	"\tuptime_ns\x18\x05 \x01(\x03R\buptimeNs\"L\n" +
	"\x17ListLocalAgentsResponse\x121\n" +
	"\x06agents\x18\x01 \x03(\v2\x19.goblin.v1.LocalAgentInfoR\x06agents\"2\n" +
	"\x15GetGlobalAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"B\n" +
	"\x16GetGlobalAgentResponse\x12(\n" +
	"\x04spec\x18\x01 \x01(\v2\x14.goblin.v1.AgentSpecR\x04spec\"*\n" +
	"\x10GetEventsRequest\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\x04R\x06cursor\"t\n" +
	"\bLogEvent\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x04R\x05index\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"@\n" +
	"\x11GetEventsResponse\x12+\n" +
	"\x06events\x18\x01 \x03(\v2\x13.goblin.v1.LogEventR\x06events\"4\n" +
	"\x19ListAgentInstancesRequest\x12\x17\n" +
	"\aspec_id\x18\x01 \x01(\tR\x06specId\"T\n" +
	"\x1aListAgentInstancesResponse\x126\n" +
	"\tinstances\x18\x01 \x03(\v2\x18.goblin.v1.AgentInstanceR\tinstances\"F\n" +
	"\x1aRegisterGlobalAgentRequest\x12(\n" +
	"\x04spec\x18\x01 \x01(\v2\x14.goblin.v1.AgentSpecR\x04spec\"N\n" +
	"\x1bRegisterGlobalAgentResponse\x12\x1b\n" +
	"\tspec_uuid\x18\x01 \x01(\fR\bspecUuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"5\n" +
	"\x18DeleteGlobalAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"L\n" +
	"\x19DeleteGlobalAgentResponse\x12\x1b\n" +
	"\tspec_uuid\x18\x01 \x01(\fR\bspecUuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xbe\x04\n" +
	"\x03Job\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"agent_type\x18\x03 \x01(\tR\tagentType\x12#\n" +
	"\rassigned_node\x18\x04 \x01(\tR\fassignedNode\x124\n" +
	"\tresources\x18\x05 \x01(\v2\x16.goblin.v1.ResourceReqR\tresources\x12A\n" +
	"\vconstraints\x18\x06 \x03(\v2\x1f.goblin.v1.Job.ConstraintsEntryR\vconstraints\x12D\n" +
	"\frequirements\x18\a \x03(\v2 .goblin.v1.Job.RequirementsEntryR\frequirements\x12%\n" +
	"\x0erestart_policy\x18\b \x01(\tR\rrestartPolicy\x12)\n" +
	"\x03env\x18\t \x03(\v2\x17.goblin.v1.Job.EnvEntryR\x03env\x1a>\n" +
	"\x10ConstraintsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a?\n" +
	"\x11RequirementsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"4\n" +
	"\x10SubmitJobRequest\x12 \n" +
	"\x03job\x18\x01 \x01(\v2\x0e.goblin.v1.JobR\x03job\"O\n" +
	"\x11SubmitJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12#\n" +
	"\rassigned_node\x18\x02 \x01(\tR\fassignedNode\"+\n" +
	"\x10DrainNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"=\n" +
	"\x11DrainNodeResponse\x12(\n" +
	"\x10migrated_job_ids\x18\x01 \x03(\tR\x0emigratedJobIds\"E\n" +
	"\x13PublishEventRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\",\n" +
	"\x14PublishEventResponse\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\"C\n" +
	"\x11MigrateJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x17\n" +
	"\ato_node\x18\x02 \x01(\tR\x06toNode\"D\n" +
	"\x12MigrateJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x17\n" +
	"\ato_node\x18\x02 \x01(\tR\x06toNode\"R\n" +
	"\x16MigrateInstanceRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x17\n" +
	"\ato_node\x18\x02 \x01(\tR\x06toNode\"p\n" +
	"\x17MigrateInstanceResponse\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x1b\n" +
	"\tfrom_node\x18\x02 \x01(\tR\bfromNode\x12\x17\n" +
	"\ato_node\x18\x03 \x01(\tR\x06toNode\"U\n" +
	"\x1aSignalAgentInstanceRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x16\n" +
	"\x06signum\x18\x02 \x01(\x05R\x06signum\"o\n" +
	"\x1bSignalAgentInstanceResponse\x12\x16\n" +
	"\x06signum\x18\x01 \x01(\x05R\x06signum\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeIdB+Z)github.com/goppydae/goblin/proto;goblinv1b\x06proto3"

var (
	file_goblin_v1_scheduler_rpc_proto_rawDescOnce sync.Once
	file_goblin_v1_scheduler_rpc_proto_rawDescData []byte
)

func file_goblin_v1_scheduler_rpc_proto_rawDescGZIP() []byte {
	file_goblin_v1_scheduler_rpc_proto_rawDescOnce.Do(func() {
		file_goblin_v1_scheduler_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_goblin_v1_scheduler_rpc_proto_rawDesc), len(file_goblin_v1_scheduler_rpc_proto_rawDesc)))
	})
	return file_goblin_v1_scheduler_rpc_proto_rawDescData
}

var file_goblin_v1_scheduler_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 41)
var file_goblin_v1_scheduler_rpc_proto_goTypes = []any{
	(*ScaleAgentRequest)(nil),           // 0: goblin.v1.ScaleAgentRequest
	(*ScaleAgentResponse)(nil),          // 1: goblin.v1.ScaleAgentResponse
	(*ListJobsRequest)(nil),             // 2: goblin.v1.ListJobsRequest
	(*JobInfo)(nil),                     // 3: goblin.v1.JobInfo
	(*ListJobsResponse)(nil),            // 4: goblin.v1.ListJobsResponse
	(*MembersRequest)(nil),              // 5: goblin.v1.MembersRequest
	(*MemberInfo)(nil),                  // 6: goblin.v1.MemberInfo
	(*MembersResponse)(nil),             // 7: goblin.v1.MembersResponse
	(*ListGlobalAgentsRequest)(nil),     // 8: goblin.v1.ListGlobalAgentsRequest
	(*ListGlobalAgentsResponse)(nil),    // 9: goblin.v1.ListGlobalAgentsResponse
	(*ListLocalAgentsRequest)(nil),      // 10: goblin.v1.ListLocalAgentsRequest
	(*LocalAgentInfo)(nil),              // 11: goblin.v1.LocalAgentInfo
	(*ListLocalAgentsResponse)(nil),     // 12: goblin.v1.ListLocalAgentsResponse
	(*GetGlobalAgentRequest)(nil),       // 13: goblin.v1.GetGlobalAgentRequest
	(*GetGlobalAgentResponse)(nil),      // 14: goblin.v1.GetGlobalAgentResponse
	(*GetEventsRequest)(nil),            // 15: goblin.v1.GetEventsRequest
	(*LogEvent)(nil),                    // 16: goblin.v1.LogEvent
	(*GetEventsResponse)(nil),           // 17: goblin.v1.GetEventsResponse
	(*ListAgentInstancesRequest)(nil),   // 18: goblin.v1.ListAgentInstancesRequest
	(*ListAgentInstancesResponse)(nil),  // 19: goblin.v1.ListAgentInstancesResponse
	(*RegisterGlobalAgentRequest)(nil),  // 20: goblin.v1.RegisterGlobalAgentRequest
	(*RegisterGlobalAgentResponse)(nil), // 21: goblin.v1.RegisterGlobalAgentResponse
	(*DeleteGlobalAgentRequest)(nil),    // 22: goblin.v1.DeleteGlobalAgentRequest
	(*DeleteGlobalAgentResponse)(nil),   // 23: goblin.v1.DeleteGlobalAgentResponse
	(*Job)(nil),                         // 24: goblin.v1.Job
	(*SubmitJobRequest)(nil),            // 25: goblin.v1.SubmitJobRequest
	(*SubmitJobResponse)(nil),           // 26: goblin.v1.SubmitJobResponse
	(*DrainNodeRequest)(nil),            // 27: goblin.v1.DrainNodeRequest
	(*DrainNodeResponse)(nil),           // 28: goblin.v1.DrainNodeResponse
	(*PublishEventRequest)(nil),         // 29: goblin.v1.PublishEventRequest
	(*PublishEventResponse)(nil),        // 30: goblin.v1.PublishEventResponse
	(*MigrateJobRequest)(nil),           // 31: goblin.v1.MigrateJobRequest
	(*MigrateJobResponse)(nil),          // 32: goblin.v1.MigrateJobResponse
	(*MigrateInstanceRequest)(nil),      // 33: goblin.v1.MigrateInstanceRequest
	(*MigrateInstanceResponse)(nil),     // 34: goblin.v1.MigrateInstanceResponse
	(*SignalAgentInstanceRequest)(nil),  // 35: goblin.v1.SignalAgentInstanceRequest
	(*SignalAgentInstanceResponse)(nil), // 36: goblin.v1.SignalAgentInstanceResponse
	nil,                                 // 37: goblin.v1.MemberInfo.TagsEntry
	nil,                                 // 38: goblin.v1.Job.ConstraintsEntry
	nil,                                 // 39: goblin.v1.Job.RequirementsEntry
	nil,                                 // 40: goblin.v1.Job.EnvEntry
	(*AgentSpec)(nil),                   // 41: goblin.v1.AgentSpec
	(*timestamppb.Timestamp)(nil),       // 42: google.protobuf.Timestamp
	(*AgentInstance)(nil),               // 43: goblin.v1.AgentInstance
	(*ResourceReq)(nil),                 // 44: goblin.v1.ResourceReq
}
var file_goblin_v1_scheduler_rpc_proto_depIdxs = []int32{
	3,  // 0: goblin.v1.ListJobsResponse.jobs:type_name -> goblin.v1.JobInfo
	37, // 1: goblin.v1.MemberInfo.tags:type_name -> goblin.v1.MemberInfo.TagsEntry
	6,  // 2: goblin.v1.MembersResponse.members:type_name -> goblin.v1.MemberInfo
	41, // 3: goblin.v1.ListGlobalAgentsResponse.agents:type_name -> goblin.v1.AgentSpec
	11, // 4: goblin.v1.ListLocalAgentsResponse.agents:type_name -> goblin.v1.LocalAgentInfo
	41, // 5: goblin.v1.GetGlobalAgentResponse.spec:type_name -> goblin.v1.AgentSpec
	42, // 6: goblin.v1.LogEvent.timestamp:type_name -> google.protobuf.Timestamp
	16, // 7: goblin.v1.GetEventsResponse.events:type_name -> goblin.v1.LogEvent
	43, // 8: goblin.v1.ListAgentInstancesResponse.instances:type_name -> goblin.v1.AgentInstance
	41, // 9: goblin.v1.RegisterGlobalAgentRequest.spec:type_name -> goblin.v1.AgentSpec
	44, // 10: goblin.v1.Job.resources:type_name -> goblin.v1.ResourceReq
	38, // 11: goblin.v1.Job.constraints:type_name -> goblin.v1.Job.ConstraintsEntry
	39, // 12: goblin.v1.Job.requirements:type_name -> goblin.v1.Job.RequirementsEntry
	40, // 13: goblin.v1.Job.env:type_name -> goblin.v1.Job.EnvEntry
	24, // 14: goblin.v1.SubmitJobRequest.job:type_name -> goblin.v1.Job
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_goblin_v1_scheduler_rpc_proto_init() }
func file_goblin_v1_scheduler_rpc_proto_init() {
	if File_goblin_v1_scheduler_rpc_proto != nil {
		return
	}
	file_goblin_v1_scheduler_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_goblin_v1_scheduler_rpc_proto_rawDesc), len(file_goblin_v1_scheduler_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   41,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_goblin_v1_scheduler_rpc_proto_goTypes,
		DependencyIndexes: file_goblin_v1_scheduler_rpc_proto_depIdxs,
		MessageInfos:      file_goblin_v1_scheduler_rpc_proto_msgTypes,
	}.Build()
	File_goblin_v1_scheduler_rpc_proto = out.File
	file_goblin_v1_scheduler_rpc_proto_goTypes = nil
	file_goblin_v1_scheduler_rpc_proto_depIdxs = nil
}
