// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: goblin/v1/scheduler_rpc.proto

package goblinv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ScaleAgentRequest changes the desired replica count for one spec.
// agent_id accepts either the spec UUID or the operator-facing name,
// matching what the CLI already passes.
type ScaleAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Replicas      int32                  `protobuf:"varint,2,opt,name=replicas,proto3" json:"replicas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScaleAgentRequest) Reset() {
	*x = ScaleAgentRequest{}
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScaleAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScaleAgentRequest) ProtoMessage() {}

func (x *ScaleAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScaleAgentRequest.ProtoReflect.Descriptor instead.
func (*ScaleAgentRequest) Descriptor() ([]byte, []int) {
	return file_goblin_v1_scheduler_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *ScaleAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ScaleAgentRequest) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

// ScaleAgentResponse reports applied state rather than a formatted
// sentence. The previous response was a string built with fmt.Sprintf,
// which a caller could only display, never assert on.
type ScaleAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpecUuid      []byte                 `protobuf:"bytes,1,opt,name=spec_uuid,json=specUuid,proto3" json:"spec_uuid,omitempty"` // 16-byte UUIDv7 of the scaled spec
	Replicas      int32                  `protobuf:"varint,2,opt,name=replicas,proto3" json:"replicas,omitempty"`                // replica count now recorded
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScaleAgentResponse) Reset() {
	*x = ScaleAgentResponse{}
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScaleAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScaleAgentResponse) ProtoMessage() {}

func (x *ScaleAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_scheduler_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScaleAgentResponse.ProtoReflect.Descriptor instead.
func (*ScaleAgentResponse) Descriptor() ([]byte, []int) {
	return file_goblin_v1_scheduler_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *ScaleAgentResponse) GetSpecUuid() []byte {
	if x != nil {
		return x.SpecUuid
	}
	return nil
}

func (x *ScaleAgentResponse) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

var File_goblin_v1_scheduler_rpc_proto protoreflect.FileDescriptor

const file_goblin_v1_scheduler_rpc_proto_rawDesc = "" +
	"\n" +
	"\x1dgoblin/v1/scheduler_rpc.proto\x12\tgoblin.v1\"J\n" +
	"\x11ScaleAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1a\n" +
	"\breplicas\x18\x02 \x01(\x05R\breplicas\"M\n" +
	"\x12ScaleAgentResponse\x12\x1b\n" +
	"\tspec_uuid\x18\x01 \x01(\fR\bspecUuid\x12\x1a\n" +
	"\breplicas\x18\x02 \x01(\x05R\breplicasB+Z)github.com/goppydae/goblin/proto;goblinv1b\x06proto3"

var (
	file_goblin_v1_scheduler_rpc_proto_rawDescOnce sync.Once
	file_goblin_v1_scheduler_rpc_proto_rawDescData []byte
)

func file_goblin_v1_scheduler_rpc_proto_rawDescGZIP() []byte {
	file_goblin_v1_scheduler_rpc_proto_rawDescOnce.Do(func() {
		file_goblin_v1_scheduler_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_goblin_v1_scheduler_rpc_proto_rawDesc), len(file_goblin_v1_scheduler_rpc_proto_rawDesc)))
	})
	return file_goblin_v1_scheduler_rpc_proto_rawDescData
}

var file_goblin_v1_scheduler_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_goblin_v1_scheduler_rpc_proto_goTypes = []any{
	(*ScaleAgentRequest)(nil),  // 0: goblin.v1.ScaleAgentRequest
	(*ScaleAgentResponse)(nil), // 1: goblin.v1.ScaleAgentResponse
}
var file_goblin_v1_scheduler_rpc_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_goblin_v1_scheduler_rpc_proto_init() }
func file_goblin_v1_scheduler_rpc_proto_init() {
	if File_goblin_v1_scheduler_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_goblin_v1_scheduler_rpc_proto_rawDesc), len(file_goblin_v1_scheduler_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_goblin_v1_scheduler_rpc_proto_goTypes,
		DependencyIndexes: file_goblin_v1_scheduler_rpc_proto_depIdxs,
		MessageInfos:      file_goblin_v1_scheduler_rpc_proto_msgTypes,
	}.Build()
	File_goblin_v1_scheduler_rpc_proto = out.File
	file_goblin_v1_scheduler_rpc_proto_goTypes = nil
	file_goblin_v1_scheduler_rpc_proto_depIdxs = nil
}
