// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: goblin/v1/scheduler.proto

package goblinv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// InstanceState is the instance lifecycle FSM (DDR-6). Transitions are
// validated by the Raft FSM; illegal transitions are rejected, and
// UUIDs of TERMINATED/ARCHIVED instances are tombstoned forever.
type InstanceState int32

const (
	// Zero value: data written before this schema surfaces as
	// UNSPECIFIED and must be rejected, never misapplied.
	InstanceState_INSTANCE_STATE_UNSPECIFIED InstanceState = 0
	InstanceState_INSTANCE_STATE_ADMITTED    InstanceState = 1 // UUID minted, committed through Raft
	InstanceState_INSTANCE_STATE_SCHEDULED   InstanceState = 2 // placement bound to a node
	InstanceState_INSTANCE_STATE_STARTING    InstanceState = 3 // dispatch in flight
	InstanceState_INSTANCE_STATE_RUNNING     InstanceState = 4
	InstanceState_INSTANCE_STATE_DRAINING    InstanceState = 5 // graceful scale-down in progress
	InstanceState_INSTANCE_STATE_STOPPING    InstanceState = 6
	InstanceState_INSTANCE_STATE_TERMINATED  InstanceState = 7 // terminal; reason says why
	InstanceState_INSTANCE_STATE_ARCHIVED    InstanceState = 8 // terminal, compacted record
)

// Enum value maps for InstanceState.
var (
	InstanceState_name = map[int32]string{
		0: "INSTANCE_STATE_UNSPECIFIED",
		1: "INSTANCE_STATE_ADMITTED",
		2: "INSTANCE_STATE_SCHEDULED",
		3: "INSTANCE_STATE_STARTING",
		4: "INSTANCE_STATE_RUNNING",
		5: "INSTANCE_STATE_DRAINING",
		6: "INSTANCE_STATE_STOPPING",
		7: "INSTANCE_STATE_TERMINATED",
		8: "INSTANCE_STATE_ARCHIVED",
	}
	InstanceState_value = map[string]int32{
		"INSTANCE_STATE_UNSPECIFIED": 0,
		"INSTANCE_STATE_ADMITTED":    1,
		"INSTANCE_STATE_SCHEDULED":   2,
		"INSTANCE_STATE_STARTING":    3,
		"INSTANCE_STATE_RUNNING":     4,
		"INSTANCE_STATE_DRAINING":    5,
		"INSTANCE_STATE_STOPPING":    6,
		"INSTANCE_STATE_TERMINATED":  7,
		"INSTANCE_STATE_ARCHIVED":    8,
	}
)

func (x InstanceState) Enum() *InstanceState {
	p := new(InstanceState)
	*p = x
	return p
}

func (x InstanceState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InstanceState) Descriptor() protoreflect.EnumDescriptor {
	return file_goblin_v1_scheduler_proto_enumTypes[0].Descriptor()
}

func (InstanceState) Type() protoreflect.EnumType {
	return &file_goblin_v1_scheduler_proto_enumTypes[0]
}

func (x InstanceState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InstanceState.Descriptor instead.
func (InstanceState) EnumDescriptor() ([]byte, []int) {
	return file_goblin_v1_scheduler_proto_rawDescGZIP(), []int{0}
}

// AgentSpec defines the desired state of a global agent. Identity is
// the spec_uuid (UUIDv7, minted by the leader at registration); name
// is the operator-facing handle and must be unique among live specs.
type AgentSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpecUuid      []byte                 `protobuf:"bytes,1,opt,name=spec_uuid,json=specUuid,proto3" json:"spec_uuid,omitempty"` // 16-byte UUIDv7
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                         // human-readable operator handle
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`                         // installed agent type, e.g. "sleeper"
	Replicas      int32                  `protobuf:"varint,4,opt,name=replicas,proto3" json:"replicas,omitempty"`
	Constraints   map[string]string      `protobuf:"bytes,5,rep,name=constraints,proto3" json:"constraints,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // node tag requirements
	Resources     *ResourceReq           `protobuf:"bytes,6,opt,name=resources,proto3" json:"resources,omitempty"`
	Strategy      string                 `protobuf:"bytes,7,opt,name=strategy,proto3" json:"strategy,omitempty"` // "spread", "binpack", "affinity"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentSpec) Reset() {
	*x = AgentSpec{}
	mi := &file_goblin_v1_scheduler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentSpec) ProtoMessage() {}

func (x *AgentSpec) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_scheduler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentSpec.ProtoReflect.Descriptor instead.
func (*AgentSpec) Descriptor() ([]byte, []int) {
	return file_goblin_v1_scheduler_proto_rawDescGZIP(), []int{0}
}

func (x *AgentSpec) GetSpecUuid() []byte {
	if x != nil {
		return x.SpecUuid
	}
	return nil
}

func (x *AgentSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentSpec) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AgentSpec) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

func (x *AgentSpec) GetConstraints() map[string]string {
	if x != nil {
		return x.Constraints
	}
	return nil
}

func (x *AgentSpec) GetResources() *ResourceReq {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *AgentSpec) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

// ResourceReq defines resource requirements
type ResourceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cpu           float64                `protobuf:"fixed64,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory        int64                  `protobuf:"varint,2,opt,name=memory,proto3" json:"memory,omitempty"` // in bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceReq) Reset() {
	*x = ResourceReq{}
	mi := &file_goblin_v1_scheduler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceReq) ProtoMessage() {}

func (x *ResourceReq) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_scheduler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceReq.ProtoReflect.Descriptor instead.
func (*ResourceReq) Descriptor() ([]byte, []int) {
	return file_goblin_v1_scheduler_proto_rawDescGZIP(), []int{1}
}

func (x *ResourceReq) GetCpu() float64 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *ResourceReq) GetMemory() int64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

// AgentInstance is the Raft-resident instance record: immutable
// identity plus scheduler-owned state. The mutable runtime locator
// (node_pid, start_epoch, pid_ns_inode) deliberately lives in gossip,
// not here (three-layer split, DDR-3/4/5).
type AgentInstance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceUuid  []byte                 `protobuf:"bytes,1,opt,name=instance_uuid,json=instanceUuid,proto3" json:"instance_uuid,omitempty"` // 16-byte UUIDv7, minted at propose time
	SpecUuid      []byte                 `protobuf:"bytes,2,opt,name=spec_uuid,json=specUuid,proto3" json:"spec_uuid,omitempty"`
	NodeId        string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	State         InstanceState          `protobuf:"varint,4,opt,name=state,proto3,enum=goblin.v1.InstanceState" json:"state,omitempty"`
	Health        *HealthStatus          `protobuf:"bytes,5,opt,name=health,proto3" json:"health,omitempty"`
	Reason        string                 `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"` // why a terminal state was entered
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentInstance) Reset() {
	*x = AgentInstance{}
	mi := &file_goblin_v1_scheduler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInstance) ProtoMessage() {}

func (x *AgentInstance) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_scheduler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInstance.ProtoReflect.Descriptor instead.
func (*AgentInstance) Descriptor() ([]byte, []int) {
	return file_goblin_v1_scheduler_proto_rawDescGZIP(), []int{2}
}

func (x *AgentInstance) GetInstanceUuid() []byte {
	if x != nil {
		return x.InstanceUuid
	}
	return nil
}

func (x *AgentInstance) GetSpecUuid() []byte {
	if x != nil {
		return x.SpecUuid
	}
	return nil
}

func (x *AgentInstance) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *AgentInstance) GetState() InstanceState {
	if x != nil {
		return x.State
	}
	return InstanceState_INSTANCE_STATE_UNSPECIFIED
}

func (x *AgentInstance) GetHealth() *HealthStatus {
	if x != nil {
		return x.Health
	}
	return nil
}

func (x *AgentInstance) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// HealthStatus
type HealthStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "healthy", "degraded", "unhealthy"
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Failures      int64                  `protobuf:"varint,3,opt,name=failures,proto3" json:"failures,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthStatus) Reset() {
	*x = HealthStatus{}
	mi := &file_goblin_v1_scheduler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthStatus) ProtoMessage() {}

func (x *HealthStatus) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_scheduler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthStatus.ProtoReflect.Descriptor instead.
func (*HealthStatus) Descriptor() ([]byte, []int) {
	return file_goblin_v1_scheduler_proto_rawDescGZIP(), []int{3}
}

func (x *HealthStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthStatus) GetFailures() int64 {
	if x != nil {
		return x.Failures
	}
	return 0
}

type RegisterAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          *AgentSpec             `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgentRequest) Reset() {
	*x = RegisterAgentRequest{}
	mi := &file_goblin_v1_scheduler_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentRequest) ProtoMessage() {}

func (x *RegisterAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_scheduler_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentRequest.ProtoReflect.Descriptor instead.
func (*RegisterAgentRequest) Descriptor() ([]byte, []int) {
	return file_goblin_v1_scheduler_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterAgentRequest) GetSpec() *AgentSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type RegisterAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgentResponse) Reset() {
	*x = RegisterAgentResponse{}
	mi := &file_goblin_v1_scheduler_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentResponse) ProtoMessage() {}

func (x *RegisterAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_scheduler_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentResponse.ProtoReflect.Descriptor instead.
func (*RegisterAgentResponse) Descriptor() ([]byte, []int) {
	return file_goblin_v1_scheduler_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterAgentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterAgentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsRequest) Reset() {
	*x = ListAgentsRequest{}
	mi := &file_goblin_v1_scheduler_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsRequest) ProtoMessage() {}

func (x *ListAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_scheduler_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentsRequest) Descriptor() ([]byte, []int) {
	return file_goblin_v1_scheduler_proto_rawDescGZIP(), []int{6}
}

type ListAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*AgentSpec           `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsResponse) Reset() {
	*x = ListAgentsResponse{}
	mi := &file_goblin_v1_scheduler_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResponse) ProtoMessage() {}

func (x *ListAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_scheduler_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsResponse) Descriptor() ([]byte, []int) {
	return file_goblin_v1_scheduler_proto_rawDescGZIP(), []int{7}
}

func (x *ListAgentsResponse) GetAgents() []*AgentSpec {
	if x != nil {
		return x.Agents
	}
	return nil
}

type GetAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // spec UUID (canonical string) or name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentRequest) Reset() {
	*x = GetAgentRequest{}
	mi := &file_goblin_v1_scheduler_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentRequest) ProtoMessage() {}

func (x *GetAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_scheduler_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentRequest.ProtoReflect.Descriptor instead.
func (*GetAgentRequest) Descriptor() ([]byte, []int) {
	return file_goblin_v1_scheduler_proto_rawDescGZIP(), []int{8}
}

func (x *GetAgentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          *AgentSpec             `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentResponse) Reset() {
	*x = GetAgentResponse{}
	mi := &file_goblin_v1_scheduler_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentResponse) ProtoMessage() {}

func (x *GetAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goblin_v1_scheduler_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentResponse.ProtoReflect.Descriptor instead.
func (*GetAgentResponse) Descriptor() ([]byte, []int) {
	return file_goblin_v1_scheduler_proto_rawDescGZIP(), []int{9}
}

func (x *GetAgentResponse) GetSpec() *AgentSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

var File_goblin_v1_scheduler_proto protoreflect.FileDescriptor

const file_goblin_v1_scheduler_proto_rawDesc = "" +
	"\n" +
	"\x19goblin/v1/scheduler.proto\x12\tgoblin.v1\"\xc7\x02\n" +
	"\tAgentSpec\x12\x1b\n" +
	"\tspec_uuid\x18\x01 \x01(\fR\bspecUuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1a\n" +
	"\breplicas\x18\x04 \x01(\x05R\breplicas\x12G\n" +
	"\vconstraints\x18\x05 \x03(\v2%.goblin.v1.AgentSpec.ConstraintsEntryR\vconstraints\x124\n" +
	"\tresources\x18\x06 \x01(\v2\x16.goblin.v1.ResourceReqR\tresources\x12\x1a\n" +
	"\bstrategy\x18\a \x01(\tR\bstrategy\x1a>\n" +
	"\x10ConstraintsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"7\n" +
	"\vResourceReq\x12\x10\n" +
	"\x03cpu\x18\x01 \x01(\x01R\x03cpu\x12\x16\n" +
	"\x06memory\x18\x02 \x01(\x03R\x06memory\"\xe3\x01\n" +
	"\rAgentInstance\x12#\n" +
	"\rinstance_uuid\x18\x01 \x01(\fR\finstanceUuid\x12\x1b\n" +
	"\tspec_uuid\x18\x02 \x01(\fR\bspecUuid\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\x12.\n" +
	"\x05state\x18\x04 \x01(\x0e2\x18.goblin.v1.InstanceStateR\x05state\x12/\n" +
	"\x06health\x18\x05 \x01(\v2\x17.goblin.v1.HealthStatusR\x06health\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\"\\\n" +
	"\fHealthStatus\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1a\n" +
	"\bfailures\x18\x03 \x01(\x03R\bfailures\"@\n" +
	"\x14RegisterAgentRequest\x12(\n" +
	"\x04spec\x18\x01 \x01(\v2\x14.goblin.v1.AgentSpecR\x04spec\"K\n" +
	"\x15RegisterAgentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x13\n" +
	"\x11ListAgentsRequest\"B\n" +
	"\x12ListAgentsResponse\x12,\n" +
	"\x06agents\x18\x01 \x03(\v2\x14.goblin.v1.AgentSpecR\x06agents\"!\n" +
	"\x0fGetAgentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"<\n" +
	"\x10GetAgentResponse\x12(\n" +
	"\x04spec\x18\x01 \x01(\v2\x14.goblin.v1.AgentSpecR\x04spec*\x99\x02\n" +
	"\rInstanceState\x12\x1e\n" +
	"\x1aINSTANCE_STATE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17INSTANCE_STATE_ADMITTED\x10\x01\x12\x1c\n" +
	"\x18INSTANCE_STATE_SCHEDULED\x10\x02\x12\x1b\n" +
	"\x17INSTANCE_STATE_STARTING\x10\x03\x12\x1a\n" +
	"\x16INSTANCE_STATE_RUNNING\x10\x04\x12\x1b\n" +
	"\x17INSTANCE_STATE_DRAINING\x10\x05\x12\x1b\n" +
	"\x17INSTANCE_STATE_STOPPING\x10\x06\x12\x1d\n" +
	"\x19INSTANCE_STATE_TERMINATED\x10\a\x12\x1b\n" +
	"\x17INSTANCE_STATE_ARCHIVED\x10\bB+Z)github.com/goppydae/goblin/proto;goblinv1b\x06proto3"

var (
	file_goblin_v1_scheduler_proto_rawDescOnce sync.Once
	file_goblin_v1_scheduler_proto_rawDescData []byte
)

func file_goblin_v1_scheduler_proto_rawDescGZIP() []byte {
	file_goblin_v1_scheduler_proto_rawDescOnce.Do(func() {
		file_goblin_v1_scheduler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_goblin_v1_scheduler_proto_rawDesc), len(file_goblin_v1_scheduler_proto_rawDesc)))
	})
	return file_goblin_v1_scheduler_proto_rawDescData
}

var file_goblin_v1_scheduler_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_goblin_v1_scheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_goblin_v1_scheduler_proto_goTypes = []any{
	(InstanceState)(0),            // 0: goblin.v1.InstanceState
	(*AgentSpec)(nil),             // 1: goblin.v1.AgentSpec
	(*ResourceReq)(nil),           // 2: goblin.v1.ResourceReq
	(*AgentInstance)(nil),         // 3: goblin.v1.AgentInstance
	(*HealthStatus)(nil),          // 4: goblin.v1.HealthStatus
	(*RegisterAgentRequest)(nil),  // 5: goblin.v1.RegisterAgentRequest
	(*RegisterAgentResponse)(nil), // 6: goblin.v1.RegisterAgentResponse
	(*ListAgentsRequest)(nil),     // 7: goblin.v1.ListAgentsRequest
	(*ListAgentsResponse)(nil),    // 8: goblin.v1.ListAgentsResponse
	(*GetAgentRequest)(nil),       // 9: goblin.v1.GetAgentRequest
	(*GetAgentResponse)(nil),      // 10: goblin.v1.GetAgentResponse
	nil,                           // 11: goblin.v1.AgentSpec.ConstraintsEntry
}
var file_goblin_v1_scheduler_proto_depIdxs = []int32{
	11, // 0: goblin.v1.AgentSpec.constraints:type_name -> goblin.v1.AgentSpec.ConstraintsEntry
	2,  // 1: goblin.v1.AgentSpec.resources:type_name -> goblin.v1.ResourceReq
	0,  // 2: goblin.v1.AgentInstance.state:type_name -> goblin.v1.InstanceState
	4,  // 3: goblin.v1.AgentInstance.health:type_name -> goblin.v1.HealthStatus
	1,  // 4: goblin.v1.RegisterAgentRequest.spec:type_name -> goblin.v1.AgentSpec
	1,  // 5: goblin.v1.ListAgentsResponse.agents:type_name -> goblin.v1.AgentSpec
	1,  // 6: goblin.v1.GetAgentResponse.spec:type_name -> goblin.v1.AgentSpec
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_goblin_v1_scheduler_proto_init() }
func file_goblin_v1_scheduler_proto_init() {
	if File_goblin_v1_scheduler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_goblin_v1_scheduler_proto_rawDesc), len(file_goblin_v1_scheduler_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_goblin_v1_scheduler_proto_goTypes,
		DependencyIndexes: file_goblin_v1_scheduler_proto_depIdxs,
		EnumInfos:         file_goblin_v1_scheduler_proto_enumTypes,
		MessageInfos:      file_goblin_v1_scheduler_proto_msgTypes,
	}.Build()
	File_goblin_v1_scheduler_proto = out.File
	file_goblin_v1_scheduler_proto_goTypes = nil
	file_goblin_v1_scheduler_proto_depIdxs = nil
}
