.nh
.TH "goblind" "1" "Jan 1970" "goblind 0.1.0-proto2g" "General Commands Manual"

.SH NAME
goblind - Goblin Distributed Supervisor Daemon


.SH SYNOPSIS
\fBgoblind [flags]\fP


.SH DESCRIPTION
Goblin Distributed Supervisor Daemon


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for goblind

.PP
\fB--id\fP=""
	Unique node identifier (default: hostname)

.PP
\fB--log-file\fP=""
	Additional rotated file sink

.PP
\fB--log-format\fP=""
	Log format: json or console

.PP
\fB--log-level\fP=""
	Log level: debug, info, warn, error

.PP
\fB--log-loki-url\fP=""
	Forward logs to a Loki endpoint

.PP
\fB--metrics-addr\fP=""
	Prometheus listen address (empty: disabled)

.PP
\fB--tls-ca\fP=""
	CA certificate for peer verification

.PP
\fB--tls-cert\fP=""
	This node's certificate

.PP
\fB--tls-key\fP=""
	This node's private key

.PP
\fB-v\fP, \fB--version\fP[=false]
	version for goblind


.SH SEE ALSO
\fBgoblind-start(1)\fP, \fBgoblind-version(1)\fP
