.nh
.TH "goblinctl" "1" "Jan 1970" "goblinctl 0.1.0-proto2g" "General Commands Manual"

.SH NAME
goblinctl-cluster-agent-delete - Delete a global agent specification


.SH SYNOPSIS
\fBgoblinctl cluster agent delete  [flags]\fP


.SH DESCRIPTION
Delete a global agent specification


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for delete


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--control-addr\fP=""
	Address of the target daemon's control plane (empty: from config)

.PP
\fB--log-level\fP=""
	Log level: debug, info, warn, error

.PP
\fB--tls-ca\fP=""
	CA certificate used to verify the daemon

.PP
\fB--tls-insecure\fP[=false]
	Skip verification (INSECURE)

.PP
\fB-v\fP, \fB--version\fP[=false]
	version for goblinctl


.SH SEE ALSO
\fBgoblinctl-cluster-agent(1)\fP
